### ISSUE TITLE
Separation of element structure from its data

### ISSUE THREAD

**Issue by ze12augusto** [ZupIT/beagle#10]
### Problem
All server driven elements are sent from the server mixing both structure and data. However, the data is often subject to change and specific for each user, while the structure is often static. Furthermore, the data can require the BFF to have to perform integrations with microservices, meaning the data often takes longer to be available then the structure.

### Example
Suppose a user profile screen, which has the user's nickname, their picture, a text containing their description and a follow button. The structure is the same for every user and static, but the data is specific and likely will require a lookup in some user microservice.

Currently, the server only sends the screen after it completes the lookup and it populates the structure with the data.

The change would allow the server to instantly send the structure and then look up and send the data, which the app will populate.

**Comment by LG95** [comment]
Part of #54.
