### ISSUE TITLE
[Integration Test] SimpleForm Action

### ISSUE THREAD

**Issue by uziasferreirazup** [ZupIT/beagle#1005]
### Scenarios:

1. Place this action inside a component called SimpleForm and check if the actions were called inside the SimpleForm component
2. Place this action inside any component and check that the app will not crash.

- [x] Android
- [x] iOS
- [x] WEB

**Comment by carlossteinzup** [comment]
The simple form in iOS needs a refactor. 
We will have to change the BFF, so all fronts will have to update

**Comment by carlossteinzup** [comment]
Updated in all fronts
