### ISSUE TITLE
[Integration Test] Component TextInput

### ISSUE THREAD

**Issue by uziasferreirazup** [ZupIT/beagle#1012]
### Scenarios:

1. Tests a TextInput with a value field populated via EXPRESSION and HARDCODED, and check if it is showing the value
2. Tests a TextInput with a placeholder(hint) populated via EXPRESSION and HARDCODED, and check if it is showing the hint;
3. Tests a TextInput with the field set as DISABLED via EXPRESSION and HARDCODED, and check if the text input is disabled;
4. Tests a TextInput with the readOnly attribute set via EXPRESSION and HARDCODED, and check if it will not be able to type in;
5. Tests a TextInput checking if the keyboard appears on focus;
6. Tests a TextInput with the type NUMBER set via EXPRESSION and HARDCODED, and check if it will show a keyboard;
7. Tests a TextInput checking if the onFocus triggers an action
8. Tests a TextInput checking if the onChange triggers an action
9. Tests a TextInput checking if the onBlur triggers an action
10. Tests that TextInput actions onChange, onFocus and onBlur and check if it is running at the right order and time.
11. Tests a TextInput with the hidden attribute set via EXPRESSION and HARDCODED, and check if it will show or hide the field

- [x] Android
- [ ] iOS
- [x] WEB

**Comment by caioortu** [comment]
We decided to remove scenarios where we check the type of the keyboard because it makes more sense to test those using unit tests.

**Comment by carlossteinzup** [comment]
We have updated the Scenarios list to better describe the behaviours desired. We are doing the same scenarios as before, but described it differently
