### ISSUE TITLE
[Integration Test] Component LazyComponent

### ISSUE THREAD

**Issue by uziasferreirazup** [ZupIT/beagle#1015]
### Scenarios:

1. Create LazyComponent component and check if it shows the initial component and after making the request it shows the new component
2. Create LazyComponent component and check if it shows the initial component and after making the request with error and check if it only shows the initial component

- [x] Android
- [x] iOS
- [ ] WEB

**Comment by carlossteinzup** [comment]
Didint close this issue since our people on WEB will have to check further the Lazy behaviour component on web since it is not the same as in Mobile.
