### ISSUE TITLE
[Integration Test] Component Image

### ISSUE THREAD

**Issue by uziasferreirazup** [ZupIT/beagle#1016]
### Scenarios:

1. Checks that the image component is rendered setting its local path HARDCODED and via EXPRESSION
2. Checks that the image component is rendered setting its remote path HARDCODED and via EXPRESSION
3. Checks that the image component is rendered setting its imagePath via EXPRESSION (old builder)

- [x] Android
- [ ] iOS
- [ ] WEB

**Comment by carlossteinzup** [comment]
We have updated the comments to better organize the tests scenarios and examples
