### ISSUE TITLE
[Integration Test] Component SimpleForm

### ISSUE THREAD

**Issue by uziasferreirazup** [ZupIT/beagle#1020]
### Scenarios:

1. Create a SimpleForm component with context and use it in the children
2. Tests the actions in the onSubmit field, create a button that triggers the SubmitForm action and check if the onSubmit actions are triggered

- [x] Android
- [x] iOS
- [x] WEB

**Comment by tayronemachadozup** [comment]
We have updated the Scenarios list to better describe the behaviours desired.

**Comment by gabcoelho** [comment]
Closed with #1140 and #1132
