### ISSUE TITLE
Collection deserialization inconsistent between web and mobile

### ISSUE THREAD

**Issue by LG95** [ZupIT/beagle#1026]
## Description

There is a divergence between different client platform's deserialization of collection-like fields from the received JSON. Specifically, the web client handles the absence of the key the same as the key having an empty JSON array (`[]`). Android and iOS fail to deserialize the absent key if the field is not optional in its schema.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Setup a server (mock or BFF) that returns the JSON from the example section (basically the touchable found at https://beagle-playground.netlify.app/#/cloud/41c859efc6a64fe195acc3c4f638266d/analytics.json).
2. Connect a Beagle Android or iOS app to this server at the exposed endpoint.
3. Get an error that `Touchable`'s `onPress` field is missing.

## Expected Results
A JSON array be valid on all platforms.

## Code example, screenshot, or link to a repository:
```json
{
    "_beagleComponent_": "beagle:touchable",
    "child": {
        "_beagleComponent_": "beagle:text",
        "text": "Click here to send the event ",
        "textColor": "blue",
        "alignment": "CENTER"
    },
    "clickAnalyticsEvent": {
        "category": "Click Touchable",
        "label": "Analytics Screen",
        "value": "Send Event Touch"
    }
}
```

**Comment by caioortu** [comment]
Could this be a playground exclusive behavior? Because if the user chooses to use our Kotlin Backend SDK, for example, it wouldn't even be possible to send this kind of JSON since the `onPress` field is mandatory.

**Comment by Tiagoperes** [comment]
I wouldn't say this is a serialization/deserialization problem. The real issue is that, in Beagle Web, `onPress` is optional for the component `beagle:touchable`, while in the other platforms it is required.

The discussion would then be: should `onPress` be required or optional? What about the button component? Considering you can also pass an empty array, does it even make it required?

**Comment by Tiagoperes** [comment]
> Could this be a playground exclusive behavior? Because if the user chooses to use our Kotlin Backend SDK, for example, it wouldn't even be possible to send this kind of JSON since the `onPress` field is mandatory.

Although this is true, we should not base the solution on the BFF. In theory, our Kotlin backend is just a helper and this JSON could be generated by anything.
