### ISSUE TITLE
ScrollView: Android/iOS differences 

### ISSUE THREAD

**Issue by tuliopereirazup** [ZupIT/beagle#11]
- Appearance: In iOS ScrollView is ```AppearanceComponent``` and in android it is not.
Add appearance to android ScrollView or remove it from iOS?

- Flex: iOS ScrollView has ```flex.grow = 1```.
Remove from iOS or add it Android?
ScrollView is not ```FlexComponent```, maybe it should be?

**Android checklist**
- [ ] ScrollView

**iOS checklist**
- [ ] ScrollView

**Schema checklist**
- [ ] Unify ScrollView

**Comment by LG95** [comment]
Two questions
1. Is the change in schema or backend?
2. Why a backend / schema change?

**Comment by matheusribeirozup** [comment]
Closing this issue because the `ScrollView` component does not need to be a `Widget`, since a child with `grow=1.0` can be used for styling instead.
