### ISSUE TITLE
Alert Action does not have null value as default for title property on backend widget

### ISSUE THREAD

**Issue by vitorbassozup** [ZupIT/beagle#1108]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Alert action widget does not have null value as default for title property on backend widget while it does on Android and iOS.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Lookup Alert widget on Backend, Android and iOS

## Expected Results
Same default on all platforms

**Comment by luismaximozup** [comment]
Apparently you can send bullet in this question yes, it does not make sense if they are not necessary, unless it is some very specific usability issue for the backend, but I believe that it must not have gone unnoticed.
