### ISSUE TITLE
Beagle - Android test coverage

### ISSUE THREAD

**Issue by othiagosouto** [ZupIT/beagle#1122]

**Comment by uziasferreirazup** [comment]
Can you provide more information about this issue?

**Comment by tuliopereirazup** [comment]
Basically this file is ignoring some important piece of code from the coverage.
https://github.com/ZupIT/beagle/blob/master/android/jacoco-android.gradle

To be more pragmatic is to add only files that is not covered by instrumented tests, but meanwhile we could add Robolectric tests for theses cases.

**Comment by uziasferreirazup** [comment]
All issues about the ignored classes were created and the code was removed.

**Comment by othiagosouto** [comment]
@tuliopereirazup @uziasferreirazup, so, what's the real android code coverage here?

**Comment by othiagosouto** [comment]
the link https://codecov.io/gh/ZupIT/beagle doesn't provide coverage for android.

**Comment by uziasferreirazup** [comment]
@othiagosouto today the report is correct, it is showing the android coverage, we are a problem with codecov because us upload the report different time because this the team will create the specific codecov by platform and will be migrating to sonar cloud.

**Comment by uziasferreirazup** [comment]
<img width="1152" alt="Screen Shot 2020-12-15 at 09 41 34" src="https://user-images.githubusercontent.com/63263091/102222441-cd598500-3eb9-11eb-87ed-1f70fd9fdab2.png">
to incrise the coverage, I was created some issues to  try get 100% coverage of code.

**Comment by uziasferreirazup** [comment]
@hernandazevedozup I signed this issue for you, as it will solve this problem with sonarcloud

**Comment by uziasferreirazup** [comment]
now we are using the sonar cloud with repositories for each module, so it has specific coverage for each platform, just check the readme
