### ISSUE TITLE
add scrollview scenario within scrollview in instrumented tests 

### ISSUE THREAD

**Issue by jenifersantoszup** [ZupIT/beagle#1159]
## Use case

To check the behavior of the scrollview component, one more test must be added that contains a scrollview within another scrollview

## Proposal

Create a scrollview with a vertical direction with another scrollview inside with a horizontal direction to make sure that both operate in their correct directions as shown in the code below:

https://run.mocky.io/v3/6d3a948d-7f5d-4591-8218-7ba4656fb8d8

**Comment by gabcoelho** [comment]
Closed in #1172
