### ISSUE TITLE
Jetpack Compose support

### ISSUE THREAD

**Issue by tuliopereirazup** [ZupIT/beagle#116]
### Describe the problem
Jetpack Compose will come with a great impact on Android Development, and it will change the way developers develop their views. The layout engine is different from View/ViewGroups that we have and support.

We have some problems to do this integration, see the following:
1. Compose does not have a public API to add Compose views inside a ViewGroup
2. As we do layout calculations inside the YogaLayout class and it is a ViewGroup, we cannot use the same class for Compose.
3. If we do not see a way to add Compose views inside a ViewGroup and use the existing YogaLayout class, the only alternative is to port the Yoga Engine to calculate Compose positions using Compose Layout mechanism.

### Expected behavior
We have two possible solutions:
1. Create a mechanism to add Compose Widgets inside a ViewGroup and everything that we have will not change and we can use YogaLayout.
2. Port all existing code inside YogaLayout to a new mechanism that works only for Compose Widgets

### Compose Useful links:
[Landing page](https://developer.android.com/jetpack/compose)
[Basic tutorial](https://developer.android.com/jetpack/compose/tutorial)
[Codelab](https://codelabs.developers.google.com/codelabs/jetpack-compose-basics/#1)
[Source code instructions](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/ui/README.md)
[Source code](https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/)

**Comment by jayvijayg** [comment]
Just dropping a comment to get a bit of clarity as the issue has been closed without any indication. So, is there a plan to support Jetpack Compose or it has been shelved and beagle will stick with the old view system?
