### ISSUE TITLE
How to provide HttpClient  in version 1.4.1?

### ISSUE THREAD

**Issue by choxxy** [ZupIT/beagle#1170]
The default Httpclient is no longer provided in version 1.4.1 in BeagleApi class.  How do I provide one?

**Comment by uziasferreirazup** [comment]
There is an example in Sample app: 
Android:
https://github.com/ZupIT/beagle/blob/master/android/sample/src/main/java/br/com/zup/beagle/sample/config/HttpClientDefault.kt

iOS:
 https://github.com/ZupIT/beagle/tree/master/iOS/Example/BeagleDemo/BeagleDemo/BeagleConfig/Network

**Comment by uziasferreirazup** [comment]
other link can help you: 
https://docs.usebeagle.io/resources/customization/beagle-for-android/http-client#introduction
https://docs.usebeagle.io/resources/customization/beagle-for-ios/networking

**Comment by choxxy** [comment]
Thanks @uziasferreirazup
