### ISSUE TITLE
SwiftUI support

### ISSUE THREAD

**Issue by theffc** [ZupIT/beagle#120]
## Describe the problem

As SwiftUI gets more mature, and iOS 13+ have more adoption, SwiftUI usage will increase, and we need support developers that want to use it.

SwiftUI seems to have good interfacing with UIKit ([apple tutorial](https://developer.apple.com/tutorials/swiftui/interfacing-with-uikit)), but we need to research and test if what we currently have inside Beagle, will work on top of this interface.

One of the main problems that we could have is view positioning/layout. We use Yoga for that, but Yoga only works with UIKit. So, we really need to investigate how to make it work with SwiftUI as well.

## Expected behaviour

Beagle should not care if users are using SwiftUI or UIKit, it should work the same way for both frameworks.

**Comment by roip890** [comment]
I also think SwiftUI can fit better for Server Driven UI because it is declarative and each view it is actually a struct.
Also for android Jetpack Compose can fit in the same way (or DSL with kotlin until compose will be in production).
