### ISSUE TITLE
 Lazy component is accepting external Path

### ISSUE THREAD

**Issue by jamessonpenhazup** [ZupIT/beagle#1213]
## Description
Lazy component is accepting external Path, for security reasons it should not accept

## Steps To Reproduce
1. Create lazy component with "https://run.mocky.io/v3/b71d4999-0138-467e-bd3e-645540c29b9f" patch.

## Expected Results
Should return an error in case of external Path.

**Comment by Tiagoperes** [comment]
We decided that this behavior is correct. Beagle Web should also allow this.

Opened issue in Beagle WEB: https://github.com/ZupIT/beagle-web-core/issues/316
