### ISSUE TITLE
Action resetStack inconsistency

### ISSUE THREAD

**Issue by lucasaraujo** [ZupIT/beagle#1224]
## Description

On Android the action `beagle:resetStack` create a new stack (identified by `controllerId` when available) containing the specified `route` and replace the current stack with the new one.
iOS doesn't create a new stack (parameter `controllerId` is not used), it just replace all the content of the current stack with the specified `route`.

## Expected Results
I don't know witch is the right behaviour but once it is defined one of the platforms should be fixed.

**Comment by Tiagoperes** [comment]
Android is correct

**Comment by Tiagoperes** [comment]
ResetApplication is also wrong on iOS
