### ISSUE TITLE
Add default error view on platforms

### ISSUE THREAD

**Issue by luisgustavozup** [ZupIT/beagle#1231]
## Description:
Android has a default error view configured, iOS and Web do not. It was decided that all platforms should also add this default error view.

## Example Android:
![Screenshot_1607435452](https://user-images.githubusercontent.com/59032921/101492793-f0c58280-3943-11eb-9ddb-c81e28e391b7.png)

**Comment by Bleil** [comment]
REACT: [Pull request](https://github.com/ZupIT/beagle-web-react/pull/176)
ANGULAR: [Pull request](https://github.com/ZupIT/beagle-web-angular/pull/225)
