### ISSUE TITLE
EPIC - Support for accessibilityHeader 

### ISSUE THREAD

**Issue by hernandazevedozup** [ZupIT/beagle#1234]
Would be nice to have supported for acessibility components on beagle the feature of telling that the component should be treated as a Title(header) 

Android 
https://stackoverflow.com/questions/40211405/android-accessibility-identify-heading

For IOS this feature is called Traits

**Comment by Tiagoperes** [comment]
In Beagle WEB, we can add the `role` attribute to the element `p`:

```html
<p role={isTitle ? 'heading' : ''}>{text}</p>
```

Source:
- https://ux.sapo.pt/acessibilidade/web-acessibilidade/aria/#:~:text=As%20especifica%C3%A7%C3%B5es%20ARIA%20introduziram%20o,navega%C3%A7%C3%A3o%20principal%20ou%20a%20pesquisa).
- https://developer.mozilla.org/pt-PT/docs/Web/Accessibility/ARIA/ARIA_Techniques

**Comment by Tiagoperes** [comment]
accebility: {
  isHeader: boolean,
}

**Comment by arthurbleilzup** [comment]
Pulls:
Angular: https://github.com/ZupIT/beagle-web-angular/pull/229
React: https://github.com/ZupIT/beagle-web-react/pull/181
