### ISSUE TITLE
Issue: IOS ScrollView produces an application crash 

### ISSUE THREAD

**Issue by yandiaszup** [ZupIT/beagle#1238]
## Description
When `scrollBarEnabled` parameter is set to true (which is the default value), the application crashes

*Crash report:*

`*** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan nan]. Layer: <CALayer:0x6000003ec120; position = CGPoint (-21 598.5); bounds = CGRect (0 0; 36 3); delegate = <_UIScrollViewScrollIndicator: 0x7ff1acd24630; frame = (-39 597; 36 3); alpha = 0; autoresize = TM; layer = <CALayer: 0x6000003ec120>>; sublayers = (<CALayer: 0x6000003ec1e0>); opaque = YES; allowsGroupOpacity = YES; opacity = 0>'`

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Declare a screen with a scroll view component
2. Run

## Expected Results
The application should not crash

**Comment by lucasaraujo** [comment]
This crash happens when using the wrong version of YogaKit, the right version is available at https://github.com/ZupIT/YogaKit (for cocoapods: `pod 'YogaKit', :git => 'https://github.com/ZupIT/YogaKit'`)
