### ISSUE TITLE
Make logger optional

### ISSUE THREAD

**Issue by victorrabelozup** [ZupIT/beagle#1277]
## Use case
Today to turn off the logger you need to set a flag that controls if the logger is used or not.

## Proposal
Instead of use a flag to control the the logic mentioned above, make it base in the instance of the logger itself.
If the logger is null it means that is turned off, and if not null that instance will be used.

This approach is used in another layer(Cache).

To maintain compatibility with other versions and avoid a breaking change the flag will still exist but with a `deprecated` flag in it so it can be removed without much impact later.

**Comment by Tiagoperes** [comment]
I though a bit more about this problem and although it makes sense for Android and iOS, it doesn't work very well for Beagle Web.

Differently from the mobile platforms, in Beagle WEB, the Beagle Service can be instantiated multiple times. If I had an option "logger" in the config, I'd be able to start the service once with "logger: null" and again with "logger: myLogger".

The Logger is a singleton that always exist, from the start of the application until the end. When setting "logger: null" in one of the instances of Beagle, I'd expect nothing to be logged for that instance. But if I start another Beagle Service with "logger: myLogger", I'd be enabling logs for every instance of the Beagle Service, including the one I explicitly told not to produce any logs.

To manage the logs in Beagle WEB I must call the singleton directly, there's no configuration to be passed to the BeagleService.

````typescript
import { logger } from '@zup-it/beagle-web'

logger.disable()
logger.enable()
logger.setLogFunction(myCustomLogManager) // used to customize the logs
```

**Comment by Tiagoperes** [comment]
Isn't this behavior already working for both iOS and Android? Since Beagle 1.4, if one doesn't setup any logger, no log will be created, right?

**Comment by uziasferreirazup** [comment]
currently, the logger is already optional, but this flag is legacy and we will depreciate it to be able to remove it in a future version.
