### ISSUE TITLE
Add support to interface Builder

### ISSUE THREAD

**Issue by victorrabelozup** [ZupIT/beagle#1278]
## Use case
I'm trying to use a server driven screen and/or a BeagleView inside my flow that was developed with interface builders(storyboard, xib). And is not supported, to navigate to a server driven screen the only way is to make it programmatically.

## Proposal
Create a `IBInspectable` property thats enable the user to configure a ViewController and/or BeagleView directly from the interface builder.

**Comment by Tiagoperes** [comment]
In today's planning we decided this wouldn't add too much value now. For this reason we decided no to implement this.

I'm closing this issue, it might be reopened after more discussion in dailies of the Beagle Foundation.
