### ISSUE TITLE
Component not rendering when using percentage margin

### ISSUE THREAD

**Issue by matheusribeirozup** [ZupIT/beagle#1279]
## Description
When using a component without defined size with vertical margin in percentage it does not render being with height 0. This might be some Yoga behavior.

## Steps To Reproduce
1. Create a Container with any children
2. Put a margin top with any percentage value
3. The children components will not appear

## Expected Results
Components must be rendered normally using margins with percentage values.

## Code example, screenshot, or link to a repository:
Json used:
```
{
  "_beagleComponent_" : "beagle:container",
    "children" : [ 
      {
      "_beagleComponent_" : "beagle:text",
        "text" : "first"
      }, {
        "_beagleComponent_" : "beagle:text",
        "text" : "second"
      }, {
        "_beagleComponent_" : "beagle:text",
        "text" : "third"
      } 
    ],
    "style" : {
      "margin" : {
        "top" : {
          "value" : 50.0,
          "type" : "PERCENT"
        }
      },
      "flex" : {
        "flexDirection" : "ROW_REVERSE"
      }
    }
}
```

Json rendered on the Web:
<img width="590" alt="Captura de Tela 2020-12-29 às 18 23 38" src="https://user-images.githubusercontent.com/57918064/103359736-2ff47880-4a97-11eb-994d-2499597ea9aa.png">

Json rendered on the Android
<img width="304" alt="Captura de Tela 2020-12-29 às 18 24 12" src="https://user-images.githubusercontent.com/57918064/103359819-5c0ff980-4a97-11eb-9e8d-c9d83565272f.png">

Using the Android Studio profiler it is possible to see that the Text components are at height 0. The same can be validated in Xcode.
<img width="424" alt="Captura de Tela 2020-12-29 às 18 25 04" src="https://user-images.githubusercontent.com/57918064/103359860-6e8a3300-4a97-11eb-9e59-d4f06098be5e.png">

**Comment by Tiagoperes** [comment]
This is fixed for Yoga, but no release has been generated yet. Should we form the repository?

**Comment by matheusribeirozup** [comment]
As we are using the fork version of yoga, this bug has been fixed. However, there is a specific behavior of flex that treats the vertical percentage with the horizontal space, so in the example of a margin top of 50% the component will not be in the half of the screen, but in the half of the screen width positioned vertically.
