### ISSUE TITLE
Actions array variable

### ISSUE THREAD

**Issue by victorrabelozup** [ZupIT/beagle#1300]
## Use case

With the new analytics the user must provide a white list with all actions that should trigger analytics logs. But this can be very difficult and a boilerplate, because the user must knows all the beagle default actions and even if the user know this he/she will need to implemente a list with all actions. This will repeat in every project.

## Proposal

To help our user, o suggest to just create a variable that is an array with all beagle default actions so if the developer wants to track all of them they just need to set this array as the white list, or can use it as base adding or removing actions to customize the analytics actions list.

**Comment by Tiagoperes** [comment]
We need feedback about the Analytics before implementing this kind of feature.
