### ISSUE TITLE
test: instrumented Textinput tests are failing

### ISSUE THREAD

**Issue by uziasferreirazup** [ZupIT/beagle#1316]
## Description
 Instrumented Textinput tests are failing.

## Steps To Reproduce

1. Run instrumentation test.
2. the Textinput  test will be failed.

## Expected Results
Passing tests.

## Code example, screenshot, or link to a repository:

<img width="438" alt="Screen Shot 2021-01-26 at 16 22 46" src="https://user-images.githubusercontent.com/63263091/105894180-c1053380-5ff2-11eb-8b91-4ec38c02b911.png">

**Comment by carlossteinzup** [comment]
I have talked to Igor about this issue and he mentioned that this issue was solved on Appium tests to be added since the old format tests using Cucumber/Espresso is being deprecated. We have agreed to close this issue since this solved already.
