### ISSUE TITLE
Button on Beagle Android is not like the Native Android

### ISSUE THREAD

**Issue by carlossteinzup** [ZupIT/beagle#1338]
## Use case

The default Button component on Beagle Android is a lot different than the Native Android Button, here are the diferences:
* The Beagle Button looks like a TextView when implemented. 
* The text label on button is not set to all caps.
* The background color on button is not showing any default color.

### Button Android Beagle
<img width="581" alt="buttonAndroid" src="https://user-images.githubusercontent.com/60155378/106929011-9bfb7980-66f2-11eb-8013-456aea8850db.png">

### Button Android Native
<img width="436" alt="buttonAndroidNative" src="https://user-images.githubusercontent.com/60155378/106929912-b84be600-66f3-11eb-9a4a-a6e47c762770.png">

## Proposal

* The proposal here is that this difference be analyzed so that we can define a priority to solve it

**Comment by uziasferreirazup** [comment]
Now the behavior follows the same of android, if the user creates a screen with only one button without putting a style it will be exactly the same as the standard of his application.
