### ISSUE TITLE
Lazy component does not handle errors in Android

### ISSUE THREAD

**Issue by carlossteinzup** [ZupIT/beagle#1342]
## Use case

In cases of error when loading the PATH listed in the lazy component, the initialState continues to appear since the error is not handled. The Lazy component on WEB and iOS handles this error and the initialState view is dismissed and an error message is loaded.

* WEB  Lazy component
![lazyWeb](https://user-images.githubusercontent.com/60155378/107043281-8c873980-67a1-11eb-8835-158aa84b0d93.png)

* iOS Lazy component
<img width="200" alt="lazyIOS" src="https://user-images.githubusercontent.com/60155378/107046027-f523e580-67a4-11eb-9aa9-56f9014477e7.png">

* Android Lazy component
<img width="600" alt="lazyAndroid" src="https://user-images.githubusercontent.com/60155378/107043661-146d4380-67a2-11eb-8493-89ec82352af0.png">

## Proposal

It seems important to consider modifying this component. When talking to a co-worker at ITAU ITI (Victor Bitencourt) I found out that they use a custom component that does exactly what Lazy does + the error handling. He gave me feedback on the importance of handling this error in their scope and suggested that we implement this functionality in ou Lazy component.

**Comment by Tiagoperes** [comment]
Android will add this beahvior

**Comment by Tiagoperes** [comment]
iOS: Lazy component error will replace the entire screen instead of just the component
