### ISSUE TITLE
SetContext on WEB does not set a value via expression

### ISSUE THREAD

**Issue by carlossteinzup** [ZupIT/beagle#1344]
## Use case

The WEB **SetContext** does not appear to be setting a new context value when this _value_ is passed via `Expression`. 

When analysing this behaviour with @Tiagoperes we have understood that this situation happens since the **ContextData** object created in WEB is set with a specific TYPE _(for example, an ArrayList)_ and that it cannot be changed after it is created, even if the **SetContext** sets a _value_ with a different TYPE _(for example, an object)_

🎇 In Android and iOS when the **SetContext** sets the **ContextData** _value_ to a different TYPE, the OLD _value_ is discarted and a new one is created with a new TYPE.

* Set Context Android -  [Android code](https://github.com/ZupIT/beagle/blob/master/backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/SetContextScreenBuilder.kt)
<img width="300" alt="setContextAndroid" src="https://user-images.githubusercontent.com/60155378/107083312-31bb0580-67d4-11eb-8688-bc333555bfde.png">

* Set Context WEB - [Web code](https://run.mocky.io/v3/3797bd95-5837-4225-8b7a-edefbbed0f5f) - rodar o código WEB no [playground](https://playground.usebeagle.io/#/demo/default-components/analytics.json?platform=react-web)
<img width="550" alt="setContextWeb" src="https://user-images.githubusercontent.com/60155378/107083360-45666c00-67d4-11eb-9c99-6d40fa597b34.png">

## Proposal

We proposse that the WEB SetContext component could set the ContextData object again discarding the OLD one.

**Comment by Tiagoperes** [comment]
Web will adapt the context

**Comment by arthurbleilzup** [comment]
Core: https://github.com/ZupIT/beagle-web-core/pull/324
React: https://github.com/ZupIT/beagle-web-react/pull/183
Angular: https://github.com/ZupIT/beagle-web-angular/pull/232
