### ISSUE TITLE
TextInput component behaves differently in WEB and MOBILE plataforms.

### ISSUE THREAD

**Issue by carlossteinzup** [ZupIT/beagle#1345]
## Use case

The **TextInput** component is not being hidden in the WEB plataform when the hidden attribute on BFF is set `true`.

The **TextInput** component in WEB does not have the attribute `**hidden: Bind<Boolean>? = null**`, that is available on  the [MOBILE](https://github.com/ZupIT/beagle/blob/master/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/TextInput.kt) component. This issue makes the **TextInput** behaves differently in WEB and MOBILE platforms

* TextInput Android - [Android code](https://github.com/ZupIT/beagle/blob/master/backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/TextInputScreenBuilder.kt)
<img width="300" alt="textInputAndroid" src="https://user-images.githubusercontent.com/60155378/107094082-2b815500-67e5-11eb-8c64-f38ad479781c.png">

* TextInput WEB - [WEB code](https://run.mocky.io/v3/89d1c637-80c6-4d3a-92ed-843581866baf)
![textInputWEB](https://user-images.githubusercontent.com/60155378/107092688-caf11880-67e2-11eb-8e02-9cf45b6861ac.png)

## Proposal

In order to make WEB and MOBILE components to behave equally it is necessary to ADD the `hidden` attribute at the WEB TextInput component

**Comment by Tiagoperes** [comment]
deprecate it in Android and iOS.

**Comment by Tiagoperes** [comment]
The tests for web must be removed

**Comment by arthurbleilzup** [comment]
Pull request on Angular:

https://github.com/ZupIT/beagle-web-angular/pull/230
