### ISSUE TITLE
Standardization of text component behaviors

### ISSUE THREAD

**Issue by luisoliveirazup** [ZupIT/beagle#135]
**Describe the problem**
When we have a text component that is applied one size, and its text is larger than the component size, on the IOS platform it shows the text and three dots, on the android platform it puts this entire text in the component

Android
![erro-android](https://user-images.githubusercontent.com/59032818/81947351-d2c6b800-95d6-11ea-8285-60fa8c4bf334.png)

IOS
![min_-_max](https://user-images.githubusercontent.com/59032818/81945453-85494b80-95d4-11ea-8694-6302b8259a8b.png)

**Expected behavior**
The solution is standardizing these text behavior on android and IOS

**Android checklist**
- [ ] change in the text component on Android

**iOS checklist**
- [ ]  change in the text component in IOS

**Comment by uziasferreirazup** [comment]
talk with the foundation team they assume the default behaviour in the current platform if you have any doubts feel free to open another issue
