### ISSUE TITLE
ListView add option turn view grid

### ISSUE THREAD

**Issue by luisgustavozup** [ZupIT/beagle#1366]
## Use case
 ListView does not have the option of turning a view grid.

## Proposal

<img width="376" alt="Screen Shot 2021-02-17 at 14 31 19" src="https://user-images.githubusercontent.com/59032921/108243662-17b2e880-712d-11eb-8573-8baeeb805287.png">

**Comment by Tiagoperes** [comment]
Hmm. This could be done via CSS in WEB, no changes would be needed to the ListView itself.

I'm not sure about iOS and Android =/

**Comment by luisgustavozup** [comment]
public struct GridView: Widget {
    public var context: Context?
    public let onInit: [Action]?
    public let dataSource: Expression<[DynamicObject]>
    public let key: String?
    public let numColumns: Int
    public let template: ServerDrivenComponent
    public let iteratorName: String?
    public let onScrollEnd: [Action]?
    public let scrollEndThreshold: Int?
    public let isScrollIndicatorVisible: Bool?
    public var widgetProperties: WidgetProperties
}
