### ISSUE TITLE
Epic: bring a proposal of new components that facilitates the developer to write its layout

### ISSUE THREAD

**Issue by uziasferreirazup** [ZupIT/beagle#1414]
New Components:

All the suggested components were born with the purpose of helping the developer to build layout in a simpler and more intuitive way, all of them are possible to do using flex, however this requires knowledge from the user.

Think about the work that the person has to read the attributes and understand that that component is going to be a column, row and etc….

--------------------

**Column**:

Currently, we have the Container component that has the same behavior by default, but I believe that the name container is not intuitive, the user needs to understand what a container is, what it does to study the documentation, while if we have a column component it is much easier :

To have one item under the other we currently use the Container component:

``` kotlin
Container (
   children = listOf (
       Text ("1"),
       Text ("2"),
       Text ("3"),
   )
)
```

Proposal:

``` kotlin
Column (
   children = listOf (
       Text ("1"),
       Text ("2"),
       Text ("3"),
   )
)
```

-----------------------

**Row**:

Currently we do not have any component that places one item next to another, we need to create a container and apply a style to be next to each other:

``` kotlin
Container (
   children = listOf (
       Text ("1"),
       Text ("2"),
       Text ("3"),
   )
) .applyFlex (
   flex = Flex (
       flexDirection = FlexDirection.ROW
   )
)
```

Proposal:

``` kotlin
Row (
   children = listOf (
       Text ("1"),
       Text ("2"),
       Text ("3"),
   )
)
```

Can also:

``` kotlin
Row (
   children = listOf (
       Text ("1"),
       Text ("2"),
       Text ("3"),
   ),
   reverse = true,
)

```

-----------------------

Center:
Currently we don't have any component that places a centralized item, we need to apply a style to be centralized:

Current:
``` kotlin
Text (
   "3",
)
   .applyFlex (
       Flex (
           justifyContent = JustifyContent.CENTER,
           alignContent = AlignContent.CENTER,
           alignSelf = AlignSelf.CENTER,
           grow = 1.0,
       ))

```

Proposal:
``` kotlin
Center (child = Text ("3"))

```

---------------------------------

Component styling:

Currently, to apply some styles to the component, the user needs to know the entire Style class, the idea is to provide something more intuitive for the user

Padding: 

Actual:
``` kotlin
    Text(text = "Text")
                .applyStyle(
                    Style(
                        padding = EdgeValue(
                            all = UnitValue(
                                value = 20.0,
                                type = UnitType.REAL,
                            ),
                        ),
                    ),
                )
```

Proposal:
``` kotlin
           Padding(
                child = Text(text = "Text"),
                padding = EdgeValue(
                    all = UnitValue(
                        value = 20.0,
                        type = UnitType.REAL,
                    ),
                ),
            ),
```

**Comment by tayronemachadozup** [comment]
Thinking about some difficulties we had when building a landing page using beagle one of them was styling the beagle component. I suggest adding the StyleId attribute to make styling the component easier.
