### ISSUE TITLE
Apply package development conventions, update dependencies, flutter and dart SDK

### ISSUE THREAD

**Issue by matheusribeirozup** [ZupIT/beagle#1430]
## Use case

Aiming at the best development of the plugin, we should follow the recommendations of the Flutter team, as well as the documentation and whenever possible apply good practices in the project. 

## Proposal

That said, we must:
- [ ] update the project's dependencies and the version of the flutter used in Beagle to (at least) 2.12 for introducing support for [null safety and other features](https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87)
- [x] follow the [conventions](https://dart.dev/guides/libraries/create-library-packages#what-makes-a-library-package) for building Flutter libraries, placing all private code inside the `lib/src` directory.

**Comment by hernandazevedozup** [comment]
https://dart.dev/null-safety/migration-guide
