### ISSUE TITLE
doubt in listview

### ISSUE THREAD

**Issue by uziasferreirazup** [ZupIT/beagle#1463]
> @uziasferreirazup By the way, I'm working on a screen using Beagle's **ListView** which populates data received from server via **SendRequest()**. I understand that in order to use ListView, I have to create a data model and bind the corresponding data fields into the cell defined in **template** attribute.
> But I'm getting stuck because there is a field (particularly **@{item.status}**, and the status can receive 1 of 5 different values) that I need to handle some business logic (maybe an if else or switch case block) to get the correct value to bind view (instead of binding **@{item.status}** directly with view), and at the moment I have no idea to achieve it.
> 
> Is there any operator or syntax in Beagle for me to accomplish the result as I expect above? Or if you have any idea to do it, please let me know.
> 
> Thanks in advance for your attention. I'm looking forward to your reply.

@uziasferreirazup sorry for this inconvenience, but can you spend some time helping me with this problem?

_Originally posted by @hoangnv11 in https://github.com/ZupIT/beagle/issues/1447#issuecomment-806056873_

**Comment by uziasferreirazup** [comment]
@hoangnv11 if you could play an example code, but we have a feature called operations that can be used within the listview.

Example:
``` KOTLIN
{
    data class Person (
            val name: String,
            val race: String,
            val planet: String,
            val isMistborn: Boolean,
            val age: Int,
            val sex: String
    )
    
    val characters = listOf(
        Person(
            name = "Kelsier",
            race = "Half-skaa",
            planet = "Scadrial",
            isMistborn = true,
            age = 38,
            sex = "male"
        ),
        Person(
            name = "Vin",
            race = "Half-skaa",
            planet = "Scadrial",
            isMistborn = true,
            age = 20,
            sex = "female"
        ),
        Person(
            name = "TenSoon",
            race = "Kandra",
            planet = "Scadrial",
            isMistborn = false,
            age = 40,
            sex = "male"
        ),
    )
    
    ListView(
        context = ContextData(id = "characters", value = characters),
        dataSource = expressionOf("@{characters}"),
        template = Container(
            children = listOf(
                Text("Name: @{uppercase(item.name)}"),
                Text("Race: @{item.race}"),
                Text("Mistborn: @{item.isMistborn}"),
                Text("Planet: @{item.planet}"),
                Text("sex: @{uppercase(item.sex)}"),
                Text("age: @{uppercase(item.age)}"),
            )
        ).applyStyle(
            Style(
                margin = EdgeValue(bottom = 20.unitReal())
            )
        )
    )
}
```

in the example above I used an operation called uppercase.
all operations beagle has by default https://docs.usebeagle.io/v1.6/api/context/operations/, this maybe will help you.
you can create custom operations: https://docs.usebeagle.io/v1.6/api/context/operations/how-to-register-a-new-operation/

**Comment by uziasferreirazup** [comment]
Example of custom operation to format status:

```
@RegisterOperation(name = "formatStatus")
class FormatStatusOperation : Operation {
    override fun execute(vararg params: OperationType?): OperationType {
        val status = params[0]?.value as String

        var formattedValue = ""
        when (status) {
            "0" -> {
                formattedValue = "Monday"
            }
            "1" -> {
                formattedValue = "Tuesday"
            }
        }

        return OperationType.TypeString(formattedValue)
    }

}
```

in my backend: 
```



{
    data class Person (
        val name: String,
        val status: String,
    )

    val characters = listOf(
        Person(
            name = "Kelsier",
            status = "0"
        ),
        Person(
            name = "Vin",
            status = "1"
        ),
    )

    ListView(
        context = ContextData(id = "characters", value = characters),
        dataSource = expressionOf("@{characters}"),
        template = Container(
            children = listOf(
                Text("Name: @{uppercase(item.name)}"),
                Text("Race: @{uppercase(formatStatus(item.status))}"),
            )
        ).applyStyle(
            Style(
                margin = EdgeValue(bottom = 20.unitReal())
            )
        )
    )
}
```
this example is very cool as you can see i called the format operation and then the uppercase at the end i will have a formatted and capitalized text

**Comment by hoangnv11** [comment]
Oh my mistake. I miss to read about Beagle operations. I've just tested it and it works like a charm.
Many thanks for your kind support!

**Comment by hoangnv11** [comment]
@uziasferreirazup can you help me close this issue? in that I think we have this problem solved.

**Comment by uziasferreirazup** [comment]
I thank you for using the lib, any questions can open issues without any problem.
