### ISSUE TITLE
How to parse data from Bind<String> to String

### ISSUE THREAD

**Issue by minmon98** [ZupIT/beagle#1467]
## Use case

I have already created a list of github users using Beagle, when I click on a cell, I want to navigate app to a screen on iOS client app with meta data through my CustomAction. The situation is I don't know how to parse "@{item.id}" (example) to (id: String) to iOS client could understand.

I need a help, thank you

**Comment by uziasferreirazup** [comment]
to do this just say that your attribute is going to be an expression and then call the `evaluate` method

```SWIFT
class CustomAction: Action {
    let id: Expression<String>?

    init(id: Expression<String>? = nil) {
        self.id = id
    }

    func execute(controller: BeagleController, origin: UIView) {

      idEvaluated = id?.evaluate(with: origin)

    }

}
```
Example in backend:

```
ListView(
        context = ContextData(
            id = "insideContext",
            value = listOf(
                Person(
                    "John",
                    0
                ),
            )
        ),
        dataSource = expressionOf("@{insideContext}"),
        template = Container(
            children = listOf(
                Button(
                    text = "",
                    onPress = listOf(
                        CustomAction(id = "@{item.name}")
                    )
                )
            )
        )
    )
    or
    
    ListView(
        dataSource = valueOf(
            listOf(
                Person(
                    "John",
                    0
                ),
            )
        ),
        template = Container(
            children = listOf(
                Button(
                    text = "",
                    onPress = listOf(
                        CustomAction(id = "@{item.name}")
                    )
                )
            )
        )
    )
```

**Comment by minmon98** [comment]
Ohh so Expression is available for iOS too, nice. Thank you a lot

**Comment by hoangnv11** [comment]
> ```swift
> evaluate
> ```

Hi Uzias, sorry for any inconvenience but which method in Android can I use to get the value wrapped in that expression?

**Comment by hoangnv11** [comment]
> to do this just say that your attribute is going to be an expression and then call the `evaluate` method
> 
> ```swift
> class CustomAction: Action {
>     let id: Expression<String>?
> 
>     init(id: Expression<String>? = nil) {
>         self.id = id
>     }
> 
>     func execute(controller: BeagleController, origin: UIView) {
> 
>       idEvaluated = id?.evaluate(with: origin)
> 
>     }
> 
> }
> ```
> 
> Example in backend:
> 
> ```kotlin
> ListView(
>         context = ContextData(
>             id = "insideContext",
>             value = listOf(
>                 Person(
>                     "John",
>                     0
>                 ),
>             )
>         ),
>         dataSource = expressionOf("@{insideContext}"),
>         template = Container(
>             children = listOf(
>                 Button(
>                     text = "",
>                     onPress = listOf(
>                         CustomAction(id = "@{item.name}")
>                     )
>                 )
>             )
>         )
>     )
>     or
>     
>     ListView(
>         dataSource = valueOf(
>             listOf(
>                 Person(
>                     "John",
>                     0
>                 ),
>             )
>         ),
>         template = Container(
>             children = listOf(
>                 Button(
>                     text = "",
>                     onPress = listOf(
>                         CustomAction(id = "@{item.name}")
>                     )
>                 )
>             )
>         )
>     )
> ```
Hi @uziasferreirazup, sorry for any inconvenience but which method in Android can I use to get the value wrapped in that expression?

**Comment by uziasferreirazup** [comment]
there is no inconvenience, including opening an issue to add this to the documentation that I appreciate.
call the method in action called `evaluateExpression` 
```KOTLIN

import android.view.View
import br.com.zup.beagle.newanalytics.ActionAnalyticsConfig
import br.com.zup.beagle.android.context.Bind
import br.com.zup.beagle.android.context.expressionOrValueOf
import br.com.zup.beagle.android.context.expressionOrValueOfNullable
import br.com.zup.beagle.android.utils.evaluateExpression
import br.com.zup.beagle.android.utils.handleEvent
import br.com.zup.beagle.android.widget.RootView
import br.com.zup.beagle.core.BeagleJson

@BeagleJson(name = "alert")
data class Alert(
    val title: Bind<String>? = null,
    val message: Bind<String>,
    val onPressOk: Action? = null,
    val labelOk: String? = null,
    override var analytics: ActionAnalyticsConfig? = null,
) : AnalyticsAction {

    constructor(
        title: String? = null,
        message: String,
        onPressOk: Action? = null,
        labelOk: String? = null,
        analytics: ActionAnalyticsConfig? = null,
    ) : this(
        title = expressionOrValueOfNullable(title),
        message = expressionOrValueOf(message),
        onPressOk = onPressOk,
        labelOk = labelOk,
        analytics = analytics
    )

    @Transient
    internal var viewFactory: ViewFactory = ViewFactory()

    override fun execute(rootView: RootView, origin: View) {
        viewFactory.makeAlertDialogBuilder(rootView.getContext())
            .setTitle(title?.let { evaluateExpression(rootView, origin, it) } ?: "")
            .setMessage(evaluateExpression(rootView, origin, message))
            .setPositiveButton(labelOk ?: rootView.getContext().getString(android.R.string.ok)) { dialogBox, _ ->
                dialogBox.dismiss()
                onPressOk?.let {
                    handleEvent(rootView, origin, it, analyticsValue = "onPressOk")
                }
            }
            .show()
    }
}

```

**Comment by uziasferreirazup** [comment]
due to this issue I created the same method on android to make it easier, I went up to PR and I will discuss it internally and probably in the next version it will be the same between platforms #1468

**Comment by hoangnv11** [comment]
> due to this issue I created the same method on android to make it easier, I went up to PR and I will discuss it internally and probably in the next version it will be the same between platforms #1468

It's very kind of you to make it easier for developers like us to use your Beagle library more effortlessly and efficiently 👍 Thank you once again!
