### ISSUE TITLE
How to show dialog using Beagle?

### ISSUE THREAD

**Issue by hoangnv11** [ZupIT/beagle#1472]
## Use case
Now I'm working on a screen that needs to show a **dialog** or a **bottom sheet** in different contexts. But I see that seemingly Beagle now has not yet to support dialog & bottom sheet on Android/iOS. Do you guys have any idea to implement it?
Thank you in advance!

## Proposal
I'm thinking of creating dialog and bottom sheet as custom widgets and showing them using custom actions (particularly show dialog & show bottom sheet).

**Comment by Tiagoperes** [comment]
Hello @hoangnv11. Beagle offers support for two simple types of dialogs:

- Alert: dialog with a title, a message and an "ok" button. ([docs](https://docs.usebeagle.io/v1.6/api/actions/alert/));
- Confirm: dialog with a title, a message, an "ok" button and a "cancel" button. ([docs](https://docs.usebeagle.io/v1.6/api/actions/confirm/)).

Both are default actions and you can find an example for each of them [here](https://playground.usebeagle.io/#/cloud/S3-b53911bd-2128-4d70-bbd0-489735cb4ef8?platform=android).

If you need a more customized dialog, then you need to implement your own, and custom actions would be the way to go.

Our default actions also don't include any form of bottom sheet. You can also use a custom action to implement one.

**Comment by hoangnv11** [comment]
> Hello @hoangnv11. Sorry for the delay, we had some holidays last week and we all took the week off.
> 
> Beagle offers support for two simple types of dialogs:
> 
> * Alert: dialog with a title, a message and an "ok" button. ([docs](https://docs.usebeagle.io/v1.6/api/actions/alert/));
> * Confirm: dialog with a title, a message, an "ok" button and a "cancel" button. ([docs](https://docs.usebeagle.io/v1.6/api/actions/confirm/)).
> 
> Both are default actions and you can find an example for each of them [here](https://playground.usebeagle.io/#/cloud/S3-b53911bd-2128-4d70-bbd0-489735cb4ef8?platform=android).
> 
> If you need a more customized dialog, then you need to implement your own. There are two ways of doing it:
> 
> 1. Create a function that places a dialog or bottom sheet on top of your screen. Use Beagle's custom actions to call it.
> 2. Create a custom widget/component that is your dialog or bottom sheet. Control wether it's visible or not by an attribute: `isOpen` for instance. Control the value of `isOpen` through a context and the action `setContext`. You can check the example for opening a modal component [here](https://playground.usebeagle.io/#/demo/component-interaction/modal.json), it's pretty much the same thing. Attention: this example only works for web, since the modal component doesn't exist in iOS or Android.
> 
> Edit: can you execute the [example I linked](https://playground.usebeagle.io/#/cloud/S3-b53911bd-2128-4d70-bbd0-489735cb4ef8?platform=android) without any trouble? We may have some firewall issues with connections from outside the american continent. Can you test it for us please? Thanks.

Don't worry, better late than never. In the past few days, I implemented custom actions that show dialog/bottom sheet. I'm trying to do the same with Navigation Drawer on Android but I don't know how to show a navigation drawer using native code in the context of a custom action. Do you have any idea about this?

Upon the example link, I tried and it says that "Could not establish a connection with the websocket service. Please, try again later." 

Thank you!

**Comment by Tiagoperes** [comment]
In a web project, I could use custom actions or custom components to achieve this. I'd say a custom action would be the best way to implement this behavior in an Android application, but I'm not the best person to help you with Beagle Android. I asked @matheusribeirozup to help you with this and he will soon answer this thread.

PS: I'm checking with the security team to fix our firewall and make the Beagle Playground available for you.

**Comment by hoangnv11** [comment]
> In a web project, I could use custom actions or custom components to achieve this. I'd say a custom action would be the best way to implement this behavior in an Android application, but I'm not the best person to help you with Beagle Android. I asked @matheusribeirozup to help you with this and he will soon answer this thread.
> 
> PS: I'm checking with the security team to fix our firewall and make the Beagle Playground available for you.
 Many thanks for your referral!

@matheusribeirozup I implemented custom actions to show a customized dialog or a bottom sheet dialog successfully (actually show an empty dialog and then load UI from Beagle Server). But now I'm stuck while creating a custom action to show a navigation drawer because I don't know how to create an instance of navigation drawer to show like normal dialogs.
Do you have any idea to help me with this problem?
Thank you in advance!

**Comment by matheusribeirozup** [comment]
> > In a web project, I could use custom actions or custom components to achieve this. I'd say a custom action would be the best way to implement this behavior in an Android application, but I'm not the best person to help you with Beagle Android. I asked @matheusribeirozup to help you with this and he will soon answer this thread.
> > PS: I'm checking with the security team to fix our firewall and make the Beagle Playground available for you.
> 
> Many thanks for your referral!
> @matheusribeirozup I implemented custom actions to show a customized dialog or a bottom sheet dialog successfully (actually show an empty dialog and then load UI from Beagle Server). But now I'm stuck while creating a custom action to show a navigation drawer because I don't know how to create an instance of navigation drawer to show like normal dialogs.
> Do you have any idea to help me with this problem?
> Thank you in advance!

Yeah! I'm doing a sample project with an implementation of navigation drawer to serve as an example for you. I apologize for the delay, but in a few hours I mark you here with the project link :). Thank you for using Beagle!

**Comment by hoangnv11** [comment]
> > > In a web project, I could use custom actions or custom components to achieve this. I'd say a custom action would be the best way to implement this behavior in an Android application, but I'm not the best person to help you with Beagle Android. I asked @matheusribeirozup to help you with this and he will soon answer this thread.
> > > PS: I'm checking with the security team to fix our firewall and make the Beagle Playground available for you.
> > 
> > 
> > Many thanks for your referral!
> > @matheusribeirozup I implemented custom actions to show a customized dialog or a bottom sheet dialog successfully (actually show an empty dialog and then load UI from Beagle Server). But now I'm stuck while creating a custom action to show a navigation drawer because I don't know how to create an instance of navigation drawer to show like normal dialogs.
> > Do you have any idea to help me with this problem?
> > Thank you in advance!
> 
> Yeah! I'm doing a sample project with an implementation of navigation drawer to serve as an example for you. I apologize for the delay, but in a few hours I mark you here with the project link :). Thank you for using Beagle!

Oh, you are my lifesaver! I'm looking forward to see your example.
Thanks a million! @matheusribeirozup

**Comment by matheusribeirozup** [comment]
Hi @hoangnv11 , I hope [this solution](https://github.com/matheusribeirozup/beagle-drawer) solves your problem! I implemented an activity with a custom navigation drawer with its content and destinations all server driven using native components. We believe that this is a very complete solution, so we will make it available as an example in our documentation. As it is a locally customized activity, the way you will open it is through a custom action. All the code is available in this repository that I mentioned above, with a readme with the implementation details.
Thanks for your patience and for bringing up pertinent questions that are making our product better. Please answer me if your problem has been solved and if so, you can close the issue :).

**Comment by hoangnv11** [comment]
Thanks for your enthusiastic support!
Then the solution is to use native navigation drawer linked with an activity.
Because the problem has been solved, I will close this issue shortly.
Thank you once again @matheusribeirozup :D
