### ISSUE TITLE
Beagle playground might not work for people outside the Americas

### ISSUE THREAD

**Issue by Tiagoperes** [ZupIT/beagle#1490]
We have some geographical restrictions imposed by the company's default firewall. For this reason, our playground is not fully accessible by people outside the Americas.

Today we made some adjustments and it should be working now, one of our users who had trouble accessing the playground was @hoangnv11. @hoangnv11 can you please check for us if it's working now? Here's the [link](https://playground.usebeagle.io/#/cloud/S3-b53911bd-2128-4d70-bbd0-489735cb4ef8/alert-dialog.json?platform=android). You should be able to see the JSONs in the editor on the left and open an Android emulator in the panel on the right.

Thanks in advance for the help.

**Comment by hoangnv11** [comment]
Hi @Tiagoperes 
I'm so pleased to confirm that the playground is now working for me. Now I can access it easily and it brings me a lot of useful examples.
Thanks for your kind support!
