### ISSUE TITLE
renderScreen using JSON causes overlapping fragments on Android 

### ISSUE THREAD

**Issue by hoangnv11** [ZupIT/beagle#1491]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Hi guys,
I'm working on a Beagle-based home screen which has Bottom Navigation View (custom widget) with 5 tabs, for each tab I will create a corresponding instance of native fragment and then render view for it using the corresponding JSON snippet.
Now I see that I have 5 instances of my fragment generated as expected but instead of the fact that each fragment should render its JSON, now there are 5 beagle fragments generated overlappingly in the first tab. And the 5th fragment stays on the top of the stack, if I press back button, the app will pop it and show the 4th fragment,...
I think that this problem is caused by the renderScreen() method, it's replacing the fragment instead of adding more fragments as my expectation.
If I use loadView() to load screen from Beagle BFF, it works properly.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Set up a BottomNavigationView as a custom widget
2. Create a CustomFragment extending Fragment with empty content, that has only a FrameLayout to render screen using JSON.
3. For each menu item of BottomNavigationView, create an instance of CustomFragment and pass into the corresponding JSON.
4. Use fragmentTransaction to add fragments above into a containerViewId
5. Set up onNavigationItemSelectedListener for BottomNavigationView

## Expected Results
Fragment for each tab are created correctly instead of overlapping in the first tab as currently.

## Code example, screenshot, or link to a repository:
I'm considering the following code snippet causes the problem:
```
internal fun ViewGroup.renderScreen(
    rootView: RootView,
    screenJson: String,
) {
    val viewModel = rootView.generateViewModelInstance<ScreenContextViewModel>()
    viewModel.clearContexts()
    val component = beagleSerializerFactory.deserializeComponent(screenJson)
    (rootView.getContext() as AppCompatActivity)
        .supportFragmentManager
        .beginTransaction()
        .replace(this.id, BeagleFragment.newInstance(component, rootView.getScreenId()))
        .addToBackStack(null)
        .commit()
}
```

**Comment by matheusribeirozup** [comment]
Hi @hoangnv11 in addition to fixing the bug you found I depreciated the `renderScreen` method and we are recommending the use of the new `loadView` method with the `screenJson` parameter. We did this only to standardize this Beagle entry point :)

**Comment by hoangnv11** [comment]
> Hi @hoangnv11 in addition to fixing the bug you found I depreciated the `renderScreen` method and we are recommending the use of the new `loadView` method with the `screenJson` parameter. We did this only to standardize this Beagle entry point :)

Yeah, thanks @matheusribeirozup. I will try it as soon as the version 1.7.0 is released!

**Comment by Tiagoperes** [comment]
@hoangnv11 version 1.7.0 has been released
