### ISSUE TITLE
How to implement ListView multi view type?

### ISSUE THREAD

**Issue by ddthanh198** [ZupIT/beagle#1523]
## Use case

I want to implement multi view type with ListView, but the template is only list of ServerDrivenComponent of one item's type.
Could you tell me some advices?

**Comment by Tiagoperes** [comment]
Hello @ddthanh198. We're currently discussing if we want this feature or not. Currently, the ListView has no support for multiple templates.

You can achieve this behavior by using the property `style.display`. Your single template can verify what you're trying to render and display only the container with the intended layout. I made you a simple example where there are 3 types of data in the listview and each of them require a different template. You can check it [here](https://playground.usebeagle.io/#/cloud/S3-13966385-145e-4b57-9204-c51ba113d79f/multiple-templates.json?platform=react-web).

`style.display` is not a perfect solution though It may cause some bugs because it only prevents renderization. A component with `display: none` will still be processed and may cause a Null Pointer Exception.  We need to further test this, but it is a way to go, it might just work for your scenario.

In any case, as I said before, multiple templates for the ListView is in our radar, we'l discuss this in our next planning.

Please leave this issue opened until we make a decision.

**Comment by ddthanh198** [comment]
Thank you! I'm looking forward to your news upon multiple-template ListView :D

**Comment by Tiagoperes** [comment]
We decided to implement the support for multiple templates in a ListView. Here's the new contract for the ListView:

```typescript
interface ListViewTemplate {
  /**
   * Condition to tell if this is the template to render or not. Optional. If omitted, we consider it to be the default template,
   * i.e, it's used whenever no other template can be used.
   */
  case?: boolean,
  /**
   * The template itself: view to render
   */
  view: BeagleUIElement,
}

interface ListView {
  direction: Direction,
  dataSource: any[],
  iteratorName?: string,
  onInit?: () => void,
  onScrollEnd?: () => void,
  scrollEndThreshold?: number,
  useParentScroll?: boolean,
  /**
   * @deprecated since v1.8, please use `templates` instead
   */
  template?: BeagleUIElement,
  /**
   * Multiple templates support. The template to use will be decided according to the property `case` of the template.
   * The first template where `case` is `true` is the template chosen to render an item. If for every template `case` is
   * `false`, then, the first template where `case` is omitted (default template) is used. 
   */
  templates?: ListViewTemplate[],
```

Considering the example I gave [here](), the JSON using the list view with support for multiple templates would be the following:

```json
{
  "_beagleComponent_": "beagle:listview",
  "direction": "VERTICAL",
  "dataSource": [
    {
      "type": "person",
      "name": "John",
      "age": 30
    },
    {
      "type": "person",
      "name": "Erika",
      "age": 25
    },
    {
      "type": "person",
      "name": "Gabriel",
      "age": 43
    },
    {
      "type": "company",
      "name": "Zup IT",
      "area": "IT"
    },
    {
      "type": "company",
      "name": "Itau",
      "area": "Banking"
    },
    {
      "type": "book",
      "category": "fantasy",
      "title": "Rythm of war",
      "collection": "The stormlight archive",
      "author": "Brandon Sanderson"
    }
  ],
  "templates": [
    {
      "case": "@{eq(item.type, 'person')}",
      "view": {
        "_beagleComponent_": "beagle:container",
        "style": {
          "display": "@{condition(eq(item.type, 'person'), 'FLEX', 'NONE')}"
        },
        "children": [
          {
            "_beagleComponent_": "beagle:text",
            "text": "PERSON:",
            "textColor": "#FF0000"
          },
          {
            "_beagleComponent_": "beagle:text",
            "text": "@{item.name} is @{item.age} years old."
          }
        ]
      }
    },
    {
      "case": "@{eq(item.type, 'company')}",
      "view": {
        "_beagleComponent_": "beagle:container",
        "children": [
          {
            "_beagleComponent_": "beagle:text",
            "text": "THIS IS A COMPANY:",
            "textColor": "#0000FF"
          },
          {
            "_beagleComponent_": "beagle:text",
            "text": "@{item.name} is a company that works on @{item.area}."
          }
        ]
      }
    },
    {
      "case": "@{eq(item.type, 'book')}",
      "view": {
        "_beagleComponent_": "beagle:container",
        "children": [
          {
            "_beagleComponent_": "beagle:text",
            "text": "A GREAT BOOK:",
            "textColor": "#008800"
          },
          {
            "_beagleComponent_": "beagle:image",
            "path": {
              "_beagleImagePath_": "remote",
              "url": "https://assets.entrepreneur.com/content/3x2/2000/20191219170611-GettyImages-1152794789.jpeg"
            },
            "style": {
              "size": {
                "width": {
                  "value": 200,
                  "type": "REAL"
                }
              }
            }
          },
          {
            "_beagleComponent_": "beagle:text",
            "text": "@{item.title} is a @{item.category} book belonging to the series @{item.collection}. It was written by the great @{item.author}"
          }
        ]
      }
    }
  ]
}
```

**Comment by hoangnv11** [comment]
@Tiagoperes Excuse me, do you have any plan to support GridView for Android & iOS?
For Android, I see that ListView available now is built by extending RecyclerView, then I think it will not cost too much effort to support GridView. I hope it's also similar to iOS.

**Comment by Tiagoperes** [comment]
@hoangnv11 yes, both ListView with support for multiple templates and the GridView are under development. They will be available in version 1.8.

**Comment by hoangnv11** [comment]
> @hoangnv11 yes, both ListView with support for multiple templates and the GridView are under development. They will be available in version 1.8.
That's great!
Can you reveal when the version 1.8 will be released?

**Comment by hoangnv11** [comment]
> @hoangnv11 yes, both ListView with support for multiple templates and the GridView are under development. They will be available in version 1.8.

That's great!
Can you reveal when the version 1.8 will be released?

**Comment by Tiagoperes** [comment]
I can't tell you a date yet, but we intend to release it before May 24.

**Comment by hoangnv11** [comment]
> I can't tell you a date yet, but we intend to release it before May 24.

Nice. We will stay tuned for your updates!

**Comment by uziasferreirazup** [comment]
@hoangnv11  we publish version 1.8 with multiple templates support you can look at our doc or any doubts open a new issue.
https://docs.usebeagle.io/v1.8/api/components/layout/listview/

**Comment by hoangnv11** [comment]
> @hoangnv11 we publish version 1.8 with multiple templates support you can look at our doc or any doubts open a new issue.
> https://docs.usebeagle.io/v1.8/api/components/layout/listview/

Thanks for your attention! I'll check it out shortly!
