### ISSUE TITLE
Strange behavior for image size in Android

### ISSUE THREAD

**Issue by Tiagoperes** [ZupIT/beagle#1525]
## Description
The size of an image is not being correctly calculates in every scenario. For some reason, in this example I created, the image has the correct width and height, but it occupies a much bigger space in the screen. I can fix this by setting both `style.size.width` and `style.size.height`. But, Android should be able to calculate the height correctly if only width is supplied, and the height case only width is supplied. This calculation should keep the original aspect ratio.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Check the example at https://playground.usebeagle.io/#/cloud/S3-13966385-145e-4b57-9204-c51ba113d79f
2. Remove the height from the only image in the json
3. See that it keep working in both React and iOS, but it destroys the layout in Android

## Expected Results
By removing the height, I expected nothing to happen to the final result.

**Comment by hoangnv11** [comment]
@Tiagoperes Related to image view, I see a bug that occurs on Android.
When I try to create a rounded image view by setting corner radius = height/2 or width/2 (height = width), Beagle doesn't create a rounded image view for Android, but it works for iOS.
Can you help me verify if this is a bug?

**Comment by luisoliveirazup** [comment]
Hello @hoangnv11 , this problem is a bug, we have already opened a issue https://github.com/ZupIT/beagle/issues/1542 and thank you very much for your contribution.
