### ISSUE TITLE
Text Padding Problem

### ISSUE THREAD

**Issue by danilorangelmg** [ZupIT/beagle#1529]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Ao tentar aplicar padding a um componente de texto do Beagle percebi que o espaço não é adicionado a esquerda, direita ou topo do elemento. Somente o padding bottom aplica o valor.

<img width="1169" alt="Captura de Tela 2021-04-30 às 18 55 29" src="https://user-images.githubusercontent.com/60155378/116758365-3f081a80-a9e6-11eb-9d9c-3d2e4017e6e8.png">

## Steps To Reproduce

1. Crie um Text com padding top, left, right, com qualquer valor no bff
2. Rodar o bff e o app

## Expected Results
Aplique o padding nas direções selecionadas

## Error
Quando selecionamos padding top, ele é aplicado no bottom(somando o mesmo), left e right não é aplicado.

## Code example, screenshot, or link to a repository:
```
Text(
        "@{item.value}",
          styleId = "Text24_FF231D19"
        ).applyStyle(
         Style(
               padding = EdgeValue(all = 16.unitReal()), borderWidth = 1.0, borderColor = "#000", cornerRadius = CornerRadius(1.0))
                  ).applyFlex(
                           Flex(
                                justifyContent = JustifyContent.CENTER)
 )
```

**Comment by uziasferreirazup** [comment]
This problem is already mapped in this issue #1445 , let's keep it open and close this one so we don't have duplicate issues
