### ISSUE TITLE
bug: the Tabbar  in IOS does not show the tab items

### ISSUE THREAD

**Issue by tayronemachadozup** [ZupIT/beagle#1534]
## Description
Tab bar in IOS does not show the images in the tab items

## Steps To Reproduce

1. Test the tabbar.json example on the playground https://playground.usebeagle.io/#/demo/default-components/tabbar.json

## Code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/64441638/116906414-9c82ae00-ac16-11eb-8651-4d547c3ef758.png)

**Comment by lucasaraujo** [comment]
Fixed in version 1.8.
<img width="902" alt="Screenshot 2021-06-10 at 10 52 47" src="https://user-images.githubusercontent.com/114565/121537538-6507de00-c9da-11eb-8676-fbf43ca5ebc6.png">
