### ISSUE TITLE
How to get JSON directly from Beagle BFF?

### ISSUE THREAD

**Issue by hoangnv11** [ZupIT/beagle#1536]
## Use case

Hi guys,
I'm working on a case that at BFF, I need to get Beagle JSON generated from a builder (for example: HomeBuilder) to preprocess before returning to client.
Normally, we can get JSON by calling APIs, but it's just for client-side. I'd like get JSON right from BFF, is there any way allowing me to achieve it?

For example, I have an API like this:
```
@GetMapping("/personal")
fun getPersonalScreen() = screenService.createPersonalScreen()
```
Clients can call this API ("/personal") to retrieve JSON and render view. But how can I get it at Beagle BFF?
Thank you!

**Comment by Tiagoperes** [comment]
You can use the Jackson Object Mapper provided by Beagle:

```kotlin
import br.com.zup.beagle.serialization.jackson.BeagleSerializationUtil

fun getViewAsJson(view: Any) {
  return BeagleSerializationUtil.beagleObjectMapper().writeValueAsString(view)
}
```

**Comment by Tiagoperes** [comment]
Did I answer your question @hoangnv11? Can I close this?

**Comment by hoangnv11** [comment]
> Did I answer your question @hoangnv11? Can I close this?

I'm so sorry for my late reply.
Yeah, I just apply your solution and it works perfectly for me. Thank you so much!
I'll close this issue immediately.
