### ISSUE TITLE
An empty container inside another container don't respect attribute grow = 1.0

### ISSUE THREAD

**Issue by andersonbadari** [ZupIT/beagle#1539]
## Description
I'm using beagle 1.6. When I have a container containing two children, both with a grow = 1, but one of the children is an empty container, the empty container have a size = 0.

## Steps To Reproduce

1. Create a mainContainer containing two children: a) a randomView and b) an emptyContainer (containing no children)
2. Make both children, randomView  and emptyContainer , have a grow = 1.0
3. Both children should fill 50% of mainContainer, but what happens is that randomView takes 100% of mainContainer, making its sibiling emptyContainer have a size = 0 (maybe because emptyContainer has no children).

## Expected Results
Both children should fill 50% of mainContainer

## Code example, screenshot, or link to a repository:
![example](https://user-images.githubusercontent.com/13127854/117145814-f061d400-ad89-11eb-91cf-73a0f557f2f8.png)

**Comment by Tiagoperes** [comment]
@andersonbadari I understood your written question, but I confess the image confused me a little bit, so I'll ignore it to be able to answer you.

I just tested 2 containers with `grow: 1` inside a parent container. I tested it for React, Android and iOS and It worked just fine, both children occupied 50% of the space available. Please, check [my code at the Beagle Playground](https://playground.usebeagle.io/#/cloud/S3-b6d59774-b1ed-472e-930d-18e30e61ce76/main.json?platform=react-web).

I'll also post the JSON I tested here in case you can't open the playground (it's very unstable recently, we're investigating the problem).

```json
{
  "_beagleComponent_": "beagle:container",
  "style": {
    "backgroundColor": "#CCCCCC",
    "size": {
      "height": {
        "value": 100,
        "type": "PERCENT"
      }
    }
  },
  "children": [
    {
      "_beagleComponent_": "beagle:container",
      "style": {
        "backgroundColor": "#FF0000",
        "flex": {
          "grow": 1
        }
      }
    },
    {
      "_beagleComponent_": "beagle:container",
      "style": {
        "backgroundColor": "#00FF00",
        "flex": {
          "grow": 1
        }
      }
    }
  ]
}
```
