### ISSUE TITLE
All HTTP exceptions are logged with a generic message

### ISSUE THREAD

**Issue by matheusribeirozup** [ZupIT/beagle#1559]
## Use case

When there is an exception in any http request, the cause of the problem is not logged, but the generic message:
`fetchData error for url $url`.

## Proposal

Showing the cause of the problem with the stack trace would give more transparency to the user. For example, when making a request of type GET with body, instead of triggering a throwable with a generic message, it would be better if the message with the cause of the problem was displayed:
`method does not support a request body: GET`

- [ ] Android
- [ ] Web

## Attention point
As the user has the possibility to build his own http client, care must be taken with changes made to the `HttpClient` contract or in the `BeagleApi` class execution logic.

**Comment by Tiagoperes** [comment]
This is also very bad in beagle Web
