### ISSUE TITLE
Problem with template in ListView at Beagle BFF

### ISSUE THREAD

**Issue by ddthanh198** [ZupIT/beagle#1570]
## Description
I'm facing a problem after upgrading Beagle BFF's library version from 1.6.0 to 1.7.0
In version 1.6.0, the module 2 is at the right of the module 1. It's OK.
But in version 1.7.0, the  module 2 is at the bottom of the module 1.

Is it a bug, or I need to specific more style? 

## Code example, screenshot, or link to a repository:
Screenshot version 1.6.0
![1 6 0-edit](https://user-images.githubusercontent.com/35637061/118622277-5bcb8d00-b7f1-11eb-9bb5-06be287fb642.PNG)

Screenshot version 1.7.0
![1 7 0](https://user-images.githubusercontent.com/35637061/118622283-5cfcba00-b7f1-11eb-830b-9a6f5f735a31.PNG)

Screenshot of the template of ListView
![Template](https://user-images.githubusercontent.com/35637061/118622287-5d955080-b7f1-11eb-9523-72c153e0d971.PNG)

**Comment by luisoliveirazup** [comment]
Hello @ddthanh198  , I did test here and we have identified that this is a bug in applyStyle and will solve it as soon as possible. Thank you very much for your contribution.

**Comment by luisoliveirazup** [comment]
@ddthanh198 We're fixing a related issue on applyStyle's method and its planned to be available soon on version 1.7.1.

**Comment by uziasferreirazup** [comment]
version `1.7.1` was generated and fixed the bug, thanks for the report. You can now update your application to get this fix.

**Comment by ddthanh198** [comment]
Wow, you fixed it so quickly.
Thank you a million for your enthusiastic support!
