### ISSUE TITLE
Trigger action on backPress button in Toolbar

### ISSUE THREAD

**Issue by carlossteinzup** [ZupIT/beagle#1598]
## Use case

It is necessary to register an action to send analytics info when the backpress button is pressed on a Toolbar.

## Proposal

- That it is possible to register a list of actions on the backPress button on the Toolbar  or 
- That an analytic event could be implemented for the backPress button when a Toolbar is configured.

-->

**Comment by josenetozup** [comment]
Another use case is to show a confirmation modal to exit the flow or not.
