### ISSUE TITLE
Add support to CDI in the Backend

### ISSUE THREAD

**Issue by otaviojava** [ZupIT/beagle#1625]
Currently, in the backend, Beagle has support for Micronaut and Spring.
Do you have a plan to add CDI in support as well?
With CDI, we'll enable to support most of the JVM frameworks:

* [Quarkus](https://quarkus.io/)
* [MicroProfile](https://microprofile.io/)
* [Jakarta EE](https://jakarta.ee/)
* [Helidon](https://helidon.io/#/)
* [TomEE](https://tomee.apache.org/)

CDI is a specification in the Java EE/Jakarta EE world. Thus, we could have support to several platforms.

**Comment by luismaximozup** [comment]
Hi Otavio! hows it going? I hope well!

As spoken before, at the moment we only have starters for Spring Boot and Micronaut. Although, it is totally possible to use other libs and frameworks for java/kotlin application development with the Beagle framework lib.

https://docs.usebeagle.io/v1.8/pt/resources/customization/beagle-for-backend/beagle-framework/

Although our sugested starters have all the necessary settings to run Beagle smoothly,  you don´t need to use them. You can check our Beagle Framework settings at our Beagle Documentation. Let me know if this helps you, and feel free to contact us again if you need any more help!.

**Comment by otaviojava** [comment]
Thank you @luismaximozup
