### ISSUE TITLE
PageIndicator accept parâmeters margin and size

### ISSUE THREAD

**Issue by josenetozup** [ZupIT/beagle#1633]
## Use case
PageIndicator of Beagle not accept change sizen and margin between dot´s

```kotlin
data class PageIndicator(
    val selectedColor: String,
    val unselectedColor: String,
    var numberOfPages: Int? = null,
    var currentPage: Bind<Int>? = null
) : PageIndicatorComponent
````

## Proposal
Change the margin between dot´s and size of dot

**Comment by matheusribeirozup** [comment]
As the `pageIndicator` is intended to be a simple component and its implementation is in fact simple, through a meeting with the team we defined that we will not change the `pageIndicator` contract to support these attributes. The recommendation is that you make your own custom component including using the Beagle implementation as a guide. We appreciate the suggestion.
