### ISSUE TITLE
Can I use Beagle library in a module and register more actions/widgets in project?

### ISSUE THREAD

**Issue by hoangnv11** [ZupIT/beagle#1664]
## Use case
Hi guys,
I've been working with Beagle for a long time and I've created many custom actions/widgets for **Android** to serve my project.
Now I'm trying to gather all these custom actions/widgets into a module (for reuse purpose in my other projects in future) and then import this module into my current project. However, I realize that if I have to create one more action/widget right in my current project (these actions/widgets should have access to resources, classes,... in my project), that action or widget will not be compiled so that it does not appear in **registeredWidgets()** in **BeagleSetup()**.

For above issue, I would like to ask whether there is anyone who ever tried this and did it successfully?
Thank you guys and look forward to seeing your responses!

### What I've done so far
1. Create a module named **ExtendedBeagleLib** that implements Beagle Library -> Write config classes such as **AppBeagleConfig**, **BeagleLoggerDefault**, **HttpClientDefault**,... -> Create custom actions/widgets
Module-scope gradle:
```
dependencies {
          ...
          api "br.com.zup.beagle:android:$beagle_version"
          kapt "br.com.zup.beagle:android-processor:$beagle_version"
          ...
}
```
2. Import this module into my current project:
Project-scope gradle:
```
dependencies {
          ...
          implementation project(':ExtendedBeagleLib')
          ...
}
```

**Comment by paulomeurerzup** [comment]
Hi @hoangnv11 thanks for your question.

We're currently working on our annotation processor to allow registering components in a multi-module project. Until this is done, you can achieve this behavior by not using Beagle's annotation processor and creating the BeagleSetup class yourself.

**Comment by hoangnv11** [comment]
> Hi @hoangnv11 thanks for your question.
> 
> We're currently working on our annotation processor to allow registering components in a multi-module project. Until this is done, you can achieve this behavior by not using Beagle's annotation processor and creating the BeagleSetup class yourself.

Thanks for your reply!
Do you mean that in future we will be able to register more components in any module within a project, right? So could you reveal when this will be available?
And for now, while I've been waiting for that release, is there any feasible way I can do to achieve the result as I describe above?

**Comment by paulomeurerzup** [comment]
Yep. It will be possible to register components in any dependency that uses Beagle's annotation processor.
We're planning to release it in version 1.9 by the end of July.

For now, the only possible way to achieve this behavior is implementing the BeagleSetup class yourself.

**Comment by uziasferreirazup** [comment]
Hey @hoangnv11 I will provide one example for you today <3

**Comment by uziasferreirazup** [comment]
my example was based on your lib called ExtendedBeagleLib:

First, you need to modify the gradle of your lib to expose the files generated for the module that will consume it, for example below:
```Gradle
android {
....
    sourceSets {
        main {
            java {
                srcDir "${buildDir.absolutePath}/generated/source/kaptKotlin/"
            }
        }
    }


}
```

Second, you need to put the beagle lib as API so you can access the beagle stuff or duplicate the dependency on the module that will consume the lib I prefer to change to API, example below:
```Gradle
dependencies {
    // Beagle
    api "br.com.zup.beagle:android:$beagle_version"
    kapt "br.com.zup.beagle:android-processor:$beagle_version"
}
```

with these changes and for you to create your app, in android project view mode you can see the generated classes by clicking on java(generated) like the photo below:
![Screen Shot 2021-06-30 at 12 06 44](https://user-images.githubusercontent.com/63263091/123985420-d7e1f480-d99b-11eb-9a06-8bb7215e51c0.png)

The class that contains everything from the beagle is called BeagleSetup let's copy all that code and create ours, with that I'll add it in the class constructor to receive the components I want to add to the beagle:

``` Kotlin
import br.com.zup.beagle.analytics.Analytics
import br.com.zup.beagle.android.action.Action
import br.com.zup.beagle.android.action.FormLocalActionHandler
import br.com.zup.beagle.android.components.form.core.ValidatorHandler
import br.com.zup.beagle.android.data.serializer.adapter.generic.TypeAdapterResolver
import br.com.zup.beagle.android.imagedownloader.BeagleImageDownloader
import br.com.zup.beagle.android.logger.BeagleLogger
import br.com.zup.beagle.android.navigation.BeagleControllerReference
import br.com.zup.beagle.android.navigation.DeepLinkHandler
import br.com.zup.beagle.android.networking.HttpClient
import br.com.zup.beagle.android.networking.HttpClientFactory
import br.com.zup.beagle.android.networking.urlbuilder.UrlBuilder
import br.com.zup.beagle.android.operation.Operation
import br.com.zup.beagle.android.setup.BeagleConfig
import br.com.zup.beagle.android.setup.BeagleSdk
import br.com.zup.beagle.android.setup.DesignSystem
import br.com.zup.beagle.android.store.StoreHandler
import br.com.zup.beagle.android.view.BeagleActivity
import br.com.zup.beagle.android.widget.WidgetView
import br.com.zup.beagle.newanalytics.AnalyticsProvider

public class MyBeagleSetup(val widgets: List<Class<WidgetView>>) : BeagleSdk {
    public override val formLocalActionHandler: FormLocalActionHandler? = null

    public override val deepLinkHandler: DeepLinkHandler =
        com.vt.extendedbeaglelib.config.AppDeepLinkHandler()

    public override val httpClient: HttpClient =
        com.vt.extendedbeaglelib.config.httpclient.HttpClientDefault()

    public override val httpClientFactory: HttpClientFactory? = null

    public override val designSystem: DesignSystem = com.vt.extendedbeaglelib.config.AppDesignSystem()

    public override val storeHandler: StoreHandler? = null

    public override val urlBuilder: UrlBuilder? = null

    public override val analytics: Analytics? = null

    public override val analyticsProvider: AnalyticsProvider? = null

    public override val logger: BeagleLogger =
        com.vt.extendedbeaglelib.config.cache.BeagleLoggerDefault()

    public override val controllerReference: BeagleControllerReference =
        ControllerReferenceGenerated()

    public override val imageDownloader: BeagleImageDownloader? = null

    public override val serverDrivenActivity: Class<BeagleActivity> =
        br.com.zup.beagle.android.view.ServerDrivenActivity::class.java as Class<BeagleActivity>

    public override val config: BeagleConfig = AppBeagleConfig()

    public override val typeAdapterResolver: TypeAdapterResolver = RegisteredCustomTypeAdapter

    public override val validatorHandler: ValidatorHandler = RegisteredCustomValidator

    public override fun registeredWidgets(): List<Class<WidgetView>> =
        merge(RegisteredWidgets.registeredWidgets(), widgets)

    public override fun registeredOperations(): Map<String, Operation> =
        RegisteredOperations.registeredOperations()

    public override fun registeredActions(): List<Class<Action>> =
        RegisteredActions.registeredActions()
}


fun <T> merge(first: List<T>, second: List<T>): List<T> {
    val list: MutableList<T> = ArrayList()
    list.addAll(first)
    list.addAll(second)
    return list
}

```

before our application we called the BeagleSetup().init() class now we will need to call the class that we created with the changes, example below:


```Kotlin
class SampleApplication : Application() {

    override fun onCreate() {
        super.onCreate()

//        BeagleSetup().init(this)
        MyBeagleSetup(listOf(LabelTwo::class.java as Class<WidgetView>)).init(this)
    }

}
```

I opened this pr for your example lib just to show you a way to do this, you can increment it and add actions for example, I believe that with that you can already have an idea of how to do it.

**Comment by uziasferreirazup** [comment]
just tweaking the @paulomeurerzup comment we are planning to release this in 1.10 which would be at the end of July, the next version 1.9 will be released this Friday but it won't be ready until then.

**Comment by uziasferreirazup** [comment]
I will close this issue, but if you have any doubts about the example, feel free to open another issue.
and to follow up the issue about the annotation processor: https://github.com/ZupIT/beagle/issues/1436

**Comment by hoangnv11** [comment]
@paulomeurerzup @uziasferreirazup I would like to thank both of you for your quick replies as well as useful information :D 
I'll stay tuned for the upcoming releases. You are doing a great job! 🥇

**Comment by hoangnv11** [comment]
@uziasferreirazup Sorry for the inconvenience but I'm trying to apply your strategy to my project but when I build application, it keeps crashing because of the following error:
```
Caused by: java.lang.ClassCastException: kotlin.reflect.jvm.internal.KClassImpl cannot be cast to java.lang.Class
```
Here is my config:
```
val registeredWidgets = listOf(
                Switch::class as Class<WidgetView>
        )
        BeagleSetup(registeredWidgets).init(this)
```

Do you face the same problem?
