### ISSUE TITLE
[Flutter] BeagleScreenRequest isn't defined

### ISSUE THREAD

**Issue by gympro159** [ZupIT/beagle#1782]
I can't find screenRequest property in BeagleWidget, and BeagleScreenRequest also isn't defined :(

****pubspec.yaml****
sdk: ">=2.7.0 <3.0.0"

 beagle: ^0.9.4-alpha
 beagle_components: ^0.9.4-alpha

****main.dart****
![image](https://user-images.githubusercontent.com/52441909/140680750-6e4078d9-2c7f-45f4-95d8-ab922de8dad4.png)

****Flutter doctor****
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.62.0)
[!] Proxy Configuration
    ! NO_PROXY is not set
[√] Connected device (2 available)

![image](https://user-images.githubusercontent.com/52441909/140680220-face8f48-4b9b-4d8e-91f8-64298250cbf8.png)

**Comment by Tiagoperes** [comment]
Hello @gympro159. Thanks for your interest. We'll be looking into it asap.

**Comment by Tiagoperes** [comment]
@gympro159, can you please downgrade to version 0.9.2-alpha and try again? Versions 0.9.3 and 0.9.4 should not have been published yet, I'll try to remove these versions from pubdev and take a look into how it happenned.

In any case, we'll have a stable version with support for yoga (flex) layout before the end of the year. Stay tuned!

**Comment by Tiagoperes** [comment]
If you want to try the most recent version (not yet published), you can point the dependency to our [GitHub project](https://github.com/ZupIT/beagle-flutter) and use [our sample](https://github.com/ZupIT/beagle-flutter/tree/main/sample) as an example.

We do recommend the use of the published and documented version though.
