### ISSUE TITLE
there are some invalid links in readme

### ISSUE THREAD

**Issue by uziassantosferreira** [ZupIT/beagle#1786]
invalid links:

`[new-app]: https://docs.usebeagle.io/get-started/new-project`
`[existing]: https://docs.usebeagle.io/get-started/using-beagle`

now these pages it is by platform with new readme doesn't need more this links

`- [**Web - Supporting libs**](https://docs.usebeagle.io/v1.10/web/libs/beagle-grpc-web/) `
this link is to install GRPC, it has nothing to do with the web installation itself

**Comment by carlossteinzup** [comment]
👋 Thank you @uziassantosferreira for raising an issue. We will investigate the matter and get back to you as soon as possible.
