### ISSUE TITLE
Erro ao tentar "setar" valor no contexto onde o path tem o msm nome que o contextId

### ISSUE THREAD

**Issue by gabrielleonardozup** [ZupIT/beagle#1810]
## Description
Num cenário onde realizamos uma ação de setContext de um valor num path cujo nome é igual ao contextId do Contexto da screen, obtivemos falha ao atualizar esse valor.

## Steps To Reproduce

1. Crie uma Screen adicionando a ela um ContextData e um id e um objeto como value onde possua um path com o mesmo id.
2. Num elemento filho qualquer dessa screen realize a ação de SetContext nesse path em especifico com qualquer valor e perceba que esse valor não será salvo no contexto.

## Expected Results
Espera-se que por mais que o path tenha o mesmo  nome do id do contexto, o seu valor seja atualizado normalmente,

## Code example, screenshot, or link to a repository:
Código de exemplo para simular o cenário no BFF:

```
Screen(
            navigationBar = NavigationBar(title = "TextSD"),
            context = ContextData(id = "text", value = mapOf("text" to "", "isValid" to false)),
            child = Container(
                    onInit = listOf(
                            SetContext(contextId = "text", value = "123", path = "text")
                    )
            ).setStyle {
                margin = EdgeValue(all = real(20.0))
            }
    )
```

Foi realizado testes e depuração no código do Beagle e acredito que achei onde possa estar o problema.
Na classe ContextDataManipulator, especificamente no seu método set, realizamos três operações em sequência:

```
val keys = createKeysFromPath(context.id, path)
val newContext = updateContextDataWithTree(context, keys)
jsonCreateTree.walkingTreeAndFindKey(newContext.value, keys, value)
```

Pelo que pude entender, criamos as chaves baseada num path especifico, com essas chaves criamos um novo contexto e em seguida caminhamos por esse contexto novo atualizando os valores.

Pois bem , o que ocorre é que quando a seguinte configuração é posta ( path com msm nome do id ) o método `createKeysFromPath` retorna uma linkedList vazia.

Na sequência quando enviamos essa lista para o método `updateContextDataWithTree` ele repassa internamente esse valor para o método :
`jsonCreateTree.createInitialTree(context.value, keys.first)`
que tenta fazer um `keys.first` que aparentemente quebra a aplicação emitindo um `NoSuchElementException`, como a execução no método set do `ContextDataManipulator` estava englobada por um bloco try/catch, isso é validado e um evento de `ContextSetResult.Failure`.

Basta entender qual era a lógica correta a ser aplicada nesse cenário e o motivo disso ocorrer.
PS: no iOS esse comportamento não ocorre

Percebi que esse cenário não era contemplado por um caso de testes na classe `ContextDataManipulatorTest` então realizei um que possa ajudar:

```
@Test
    fun `set Should change value correctly when path has same name as contextId`() {
        val contextIdMock = "postalCode"
        val jsonMock = JSONObject()
        jsonMock.put(contextIdMock, "123")
        jsonMock.put("isValid", false)
        val contextMock = ContextData(
            id = contextIdMock,
            value = jsonMock
        )

        val pathMock = contextIdMock
        val subject = contextDataManipulator.set(context = contextMock,value= "321", path = pathMock)

        assertTrue { subject is ContextSetResult.Succeed }
        val newContext = ((subject as ContextSetResult.Succeed ).newContext.value as JSONObject).getString(contextIdMock)
        assertEquals("321", newContext)
    }
```

Segue abaixo prints dos pontos cruciais citados:
[print 1](https://imgur.com/mSD7qCE)
[print 2](https://imgur.com/oOhUYUr)
[print 3](https://imgur.com/XJilJPX)

**Comment by Tiagoperes** [comment]
Reproduction in Playground:

https://playground.usebeagle.io/#/cloud/S3-a972c363-cf12-42c1-ab19-9e46f9de36a5?platform=android
