### ISSUE TITLE
Ability to bold a text or apply font styles

### ISSUE THREAD

**Issue by Vipank** [ZupIT/beagle#1817]
Hi team, it would really be helpful if we could add functionality to apply different styles for example bolding a text. Currently, the styles are very limited and don't serve much purpose.

Thanks

**Comment by Tiagoperes** [comment]
Sorry for the delayed response @Vipank.

Thank you for the suggestion, but we have the mindset now that real applications will use their own design system and it's not very productive for us to invest much time in the default Beagle components, they will be replaced anyway.

A better solution would be for us to implement a well-known design system that could actually be used by real applications, like a Material Design lib of components. Then, adding options like font-family and font-weight could be very useful. Unfortunately, we don't have the resources (time and team) to build such lib.

Right now, we expect the user to develop its own text component (custom component) or use a styleId to refer to a theme defined in the frontend.

**Comment by Vipank** [comment]
Hi Tiago, thanks for your email. We were planning to use beagle in our
company. But I had a few queries about it. Would it be possible for you to
help us with that?

Thanks
Vipan
