### ISSUE TITLE
beagle-spring-starter interferes with pre-existing endpoints

### ISSUE THREAD

**Issue by manosbatsis** [ZupIT/beagle#1822]
## Use case

Using `beagle-spring-starter` seems to interfere with existing REST, JSON-API, GraphQL etc. endpoints.

## Proposal

Add a configuration property or HOWTO for restricting Beagle's URL matches based on: 

1. URL pattern(s) e.g. `/sdui/**` and/or
2. existence of `BeaglePlatformUtil.BEAGLE_PLATFORM_HEADER` as an HTTP request header

**Comment by Tiagoperes** [comment]
Thanks for reporting. @hernandazevedozup will check this asap.

**Comment by hernandazevedozup** [comment]
The fix for this issue has been released on [2.0.2 ](https://github.com/ZupIT/beagle-backend-kotlin/releases/tag/2.0.2)
