### ISSUE TITLE
Creating listview programmatically will result in crash with "java.lang.IllegalArgumentException: RecyclerView Id can't be -1"

### ISSUE THREAD

**Issue by brianchu** [ZupIT/beagle#1842]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I have a Compose view to include a listview (as AndroidView) and pass in the data (value) directly as dataSource. However, when it scrolls to the end, the app crash with
```

  java.lang.IllegalArgumentException: RecyclerView Id can't be -1
                 	at br.com.zup.beagle.android.view.viewmodel.ListViewIdViewModel.markHasCompletelyLoaded(ListViewIdViewModel.kt:147)
                 	at br.com.zup.beagle.android.components.ListView$configRecyclerViewScrollListener$1.onScrolled(ListView.kt:175)
                 	at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5347)


```
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a native component using Compose
2. Create a listview and pass in all correct data.
3. The `dataSource` is direct data, so there is no expression, just value (array of hash map)
4. It will show correctly when start 
5. Scroll to the end, it crashes.

## Expected Results
No crash when scrolling in any way.

The view.id is -1 (NO ID) and component's id doesn't seem to set.

## Code example, screenshot, or link to a repository:

```
@Composable
fun ListViewWrapper(state: SomeExtendListViewData, rootView: RootView) {

    Box() {
        state.dataSource?.let { data: List<Any> ->
            AndroidView(
                factory = {
                    val listView = ListView(
                        direction = state.direction,
                        context = state.context,
                        onInit = state.onInit,
                        dataSource = Bind.Value(data),
                        templates = state.templates,
                    )

                    listView.buildView(rootView)
                }
            )
        }
    }
}
```

**Comment by brianchu** [comment]
The reason why I pass in data directly is because I want to manipulate them before giving to the list view. I tried onInit first but it won't work since it won't happen until window is attached. so I think since I create my own Compose to wrap a Beagle component, I will bind the data myself and once I get the data and after I manipulate them, I pass it to the list view created programmatically.

**Comment by brianchu** [comment]
Thanks for your reply.

How do you add custom action to the `dataSource` of a listview?

`"dataSource": "@{fixdata(@{data.foo.bar})"`

doesn't work for me as my operation (fixdata) never execute.

**Comment by brianchu** [comment]
😆 It should be
"dataSource": "@{fixdata(data.foo.bar)}"
This one works perfectly.

**Comment by Tiagoperes** [comment]
I'm glad it worked Brian! I'll still check the index problem.

**Comment by brianchu** [comment]
- I also did a similar one in Android view (not Compose), very similar to gridView and it has no issue.
- I added a BeagleFlexView to wrap around the listView in my Compose example, same issue. It look like:

`@Composable
fun ListViewWrapper(state: MyState, rootView: RootView) {

    Box() {
        state.dataSource?.let { data: List<Any> ->
            AndroidView(
                factory = {
                    val flexView = BeagleFlexView(rootView)
                    val listView: ListView = ListView(
                        direction = state.direction,
                        context = state.context,
                        onInit = state.onInit,
                        dataSource = Bind.Value(data),
                        templates = state.templates,
                    )

                    flexView.addView(listView.buildView(rootView), Style())
                    flexView
                }
            )
        }
    }
}`

**Comment by Tiagoperes** [comment]
Since this problem only happens with Jetpack Compose, I consider fixing it as a new feature. As stated before, Beagle was not initially made for Compose.

Unfortunately we don't have a dedicated team for Beagle right now and we'll only be fixing critical bugs for the time being. Community pull requests will be still welcomed.
