### ISSUE TITLE
ScrollView comportamento aleatório

### ISSUE THREAD

**Issue by vitorbassozup** [ZupIT/beagle#187]
**Describe the problem**
ScrollView com uma lista de ComposeComponent que contém um Text e um NetworkImage causa comportamento inesperado onde a lista fica com tamanho diferente cada vez que a tela é acessada e o Component Text pode ou não aparecer. 

**Expected behavior**
Uma lista "scrolável" do ComposeComponent, sempre do mesmo tamanho e mostrando todos seus elementos (Text) 
![scrollview2](https://user-images.githubusercontent.com/61196469/82945313-132d1b00-9f73-11ea-9ebc-1ce18c8ec8fd.gif)

**Comment by lucka3s** [comment]
I could reproduce the problem but after updating the branch with new code from the master the issue apparently was resolved. I will keep watching to ensure it does not return.
