### ISSUE TITLE
Remove the direction property

### ISSUE THREAD

**Issue by luisgustavozup** [ZupIT/beagle#188]
This property is not used much, and its use is confusing when you also have start and end.

The possible solution is to delete it and when you use it, implement it again

**Comment by uziasferreirazup** [comment]
@luisgustavozup  this issue not follow the pattern to create issue, can you adjust?

**Comment by uziasferreirazup** [comment]
Please add the labels and the project

**Comment by lucasaraujo** [comment]
Closed by #189 #191 #219
