### ISSUE TITLE
Montagem da Uri no FormSubmitter

### ISSUE THREAD

**Issue by vitorbassozup** [ZupIT/beagle#203]
**Describe the problem**
Quando submeter um Form com input de texto usando FormRemoteAction por método GET, a montagem da Uri inclue os parametros do Form de forma não encodada (espaços eram string de espaço literal em vez de %20, ex: '?title=iron man') o que faz com que ocorra uma exceção no android ao tentar mandar a request desse tipo; E campos não preenchidos são incluídos como String vazia (ex: '&character=') em vez de não serem incluídos, podendo causar comportamento inesperado no backend (onde se espera um valor nulo ao vez de uma string vazia).
Ex de uri montado atual: http://10.0.2.2:8081/v1/comics?title=iron man&character=

**Expected behavior**
A string correspondente ao path deveria estar encodada no formato uri e inputs não preenchidos não deveriam ser incluidos no URI da requisição GET
uri esperado: http://10.0.2.2:8081/v1/comics?title=iron%20man

**Comment by uziasferreirazup** [comment]
@vitorbassozup can you write the issues in english? because this is the language speaking in the project
