### ISSUE TITLE
EPIC - Refactor ListView to support rendering a template over a list iteration 

### ISSUE THREAD

**Issue by Tiagoperes** [ZupIT/beagle#210]
### Problem
As pointed by @hernandazevedozup and discussed in the meeting of 05/29/2020, we need a way to improve the performance of our lists that repeats a template over a number of items. This will help us to utilize cache more efficiently, have a smaller json and have a better list performance in mobile devices.

### Changes
- Attribute `dataSource` is an array and represents the list we'll iterate over. Just like any other attribute, we must be able to use an expression, replacing it by an array in a context. 
- Attribute `onInit`, just like the container, should run this event as soon as the component is rendered. `onInit` must be related to an action.
- Attribute `template` will be the component rendered for each item in `dataSource`.

The following points should be discussed further:
- Attribute `scrollEndThreshold` will be the threshold that will define how many percent to trigger the `onScrollEnd` event.
- Attribute `onScrollEnd` will be responsible to execute a list of actions whenever the scrolls reaches its threshold.

The template can contain expressions referring to the current item in the data source. These expressions must follow the same syntax of the context feature. The current item can be referred to by the word `item`.

`item` now becomes a reserved word and can not be used as a context id.

### Example

```javascript
{
  _beagleComponent_: 'beagle:listview',
  _context_: {
    id: 'clients',
    value: [],
  },
  onInit: {
    _beagleAction_: 'beagle:sendRequest',
    url: '/api/clients',
    onSuccess: {
      _beagleAction_: 'beagle:setContext',
      value: '@{onSuccess.data}',
    },
  },
  dataSource: '@{clients}', // must be an array or expression (referring to a context id)
  template: {
    _beagleType_: 'beagle:container',
    children: [
      {
        _beagleType_: 'beagle:text',
        text: 'O nome do cliente é @{item.name} e sua idade é @{item.age} @{currentDate}',
      },
      {
        _beagleType_: 'beagle:button',
        text: 'Teste @{client.name}',
      },
    ],
  },
}
```

- [ ]  Web https://github.com/ZupIT/beagle-web-components/issues/6
- [ ] Android: #542

**Comment by Tiagoperes** [comment]
Novos parâmetros par o listview (paginação)

- onScrollEnd: Action
- scrollEndThreshold: Int (0 triga o evento logo de cara, 100 triga o evento quando o scroll chega ao fim apenas, valores intermediários indicam a progressão do scroll em porcentagem). Opcional, valor padrão é 100.

**Comment by Tiagoperes** [comment]
**New attribute:**

- useParentScroll: boolean. Default is false. When true, the listview won't use its own scroll, instead it will respect the parent scrollView (first ascendant, not necessarily the first parent).

**Styling**

The listview should support the style attribute.

**Comment by Tiagoperes** [comment]
**Question:**

If `useParentScroll` is true, how should `onScrollEnd` and `scrollEndThreshold` behave?

**Comment by carolinegoncalveszup** [comment]
Imagine the following situation, the `onScrollEnd` is an event that calls a sendRequest action and  `scrollEndThreshold` is 50. When the user scrolls to 50% of the screen the request is sent, but the user keeps scrolling and while the request hasn't finished, the condition of the scroll percentage is still true (the percentage of the scroll is still greater than 50%). Without any conditions before calling onScrollEnd, the request will be sent multiple time what may cause a problem. 

We propose avoid calling onScrollEnd again if the dataSource hasn't changed. The idea is that if we called onScrollEnd once (so the scrollEndThreshold is reached), it will only be called again once the datasource has changed and scrollEndThreshold has already been reached for the new datasource. 

Therefore, for the situation above, the request will only be sent a second time if the first request changed somehow the datasource. Also, we will not keep calling onScrollEnd while the request hasn't finished.

What do you think? Does this rule to avoid calling onScrollEnd multiple times makes sense?

**Comment by Tulioh** [comment]
I think this make sense and should be implemented on each platform, but we need to document that point to make things clear.

**Comment by Tiagoperes** [comment]
It does make sense for me, in summary, onScrollEnd would be an event that occurs only once per dataset.

**Comment by Tiagoperes** [comment]
We need a name for an optional attribute that will be name of the implicit context created for each item. By fefault, the name will be `item`.

We need this because, considering nested listviews, sometimes we need to make a reference to the item of the external listview instead of the current,  more internal, listview.

We need suggestions for the name of this new attribute, please use this issue to give them.

**Comment by LG95** [comment]
We need to review which fields are bindable, specifically when we have a sealed class like type as the bindable. For example, `ImagePath` is the bindable field in `Image`. If in my context I only have strings, defining an expression that binds to `ImagePath` becomes cumbersome.

**Solution 1**
Make the fields in such classes bindable instead of the class itself.

Example

Replace
```kotlin
data class Image(val path: Bind<ImagePath>, val mode: ImageContentMode? = null) : Widget()

sealed class ImagePath(val url: String?, val placeholder: Local? = null) {
    class Local internal constructor(webUrl: String?, val mobileId: String?) : ImagePath(webUrl)
    class Remote(remoteUrl: String, placeholder: Local? = null) : ImagePath(remoteUrl, placeholder)
}
```
with
```kotlin
data class Image(val path: ImagePath, val mode: ImageContentMode? = null) : Widget()

sealed class ImagePath(val url: Bind<String>?, val placeholder: Local? = null) {
    class Local internal constructor(webUrl: Bind<String>?, val mobileId: Bind<String>?) : ImagePath(webUrl)
    class Remote(remoteUrl: Bind<String>, placeholder: Local? = null) : ImagePath(remoteUrl, placeholder)
}
```

**Comment by LG95** [comment]
`outerItem`

**Comment by hernandazevedozup** [comment]
`listVar`

**Comment by hernandazevedozup** [comment]
`listItemVar`

**Comment by theffc** [comment]
`templateContextName`

**Comment by Tiagoperes** [comment]
eu gostei de `templateContextName`, mas eu retiraria o `template`, deixando apenas `contextName`.

Outras sugestões seriam:
- `itemName`
- `iterator`
- `iteratorName`
- `iteratorVariable`
- `iterationVariable`
- `itemAs`

`outerItem` eu não concordo, pois não estamos nomeando nada externo ao listview, o nome que estamos dando é para os itens do listview corrente.

`listVar` faz sentido, mas eu não sou muito fã do nome. Não tenho nada contra nem a favor, haha.

**Comment by theffc** [comment]
o `template` acho válido utilizar porque pelo que entendi essa variável só é importante para o template, seu valor afeta única e exclusivamente coisas que estão dentro do template, até pensei em colocar essa variável dentro da key template, mas acho que ficaria meio estranho

**Comment by Tiagoperes** [comment]
@theffc j'ai compris, mais en fait, tout les paramètres du listview concernent seulement le template...

lol, just kidding, we should stop changing languages mid-issue. Let's write english only =p

I get your point, but other parameters in the listview affect only the template. Take `dataSource`, for instance, it affects only the template and we didn't prefixed it with `template`.

**Comment by lucasaraujo** [comment]
`contextName`

**Comment by Tiagoperes** [comment]
It has been decided (daily of today) that the name for the property will be `iteratorName`

**Comment by Tiagoperes** [comment]
Definitions about the event onScrollEnd:

**It can get called only once per dataset**
The onScrollEnd gets called, while the dataset property doesn't change, this event can't be called again. This is to avoid calling the same action (probably a request) over and over again while the scroll position meets the scrollEndThreshold criteria. 

Question: what about error cases? How do we handle them? Think of an infinite scroll, how should the error on a request be handled?

**It should be called anyway if the screen content is not enough to create a scroll**
To support any number of devices, if the list is not big enough to create a scroll, the event "onScrollEnd" should be called. Of course, respecting the first rule, where the event gets called only once per dataset.

**Comment by Tiagoperes** [comment]
### About the ids inside a template

If an id is set inside a template, multiple elements will have the same id, which is wrong. One way we can fix this is to allow the `id` to accept expressions, so, inside the template, when we need to add an id, we can do stuff like `"id": "container_${item.id}"`.

**Comment by Tiagoperes** [comment]
With exception of the `bindable ids` (we still have to make sure this is the solution we're going with), the new listview has been implemented in beagle web. All related PRs are linked above.

We have several examples in the Beagle Playground Beta. If you note any inconsistence, please, let us know! Also, this is a good set of payloads to test the implementations in any platforms and make sure all are behaving the same.

https://beagle-playground-beta.netlify.app/#/demo/listview

**Comment by Tiagoperes** [comment]
> ### About the ids inside a template
> If an id is set inside a template, multiple elements will have the same id, which is wrong. One way we can fix this is to allow the `id` to accept expressions, so, inside the template, when we need to add an id, we can do stuff like `"id": "container_@{item.id}"`.
> 
> Does everybody have another solution? Do you guys think this is a good way to solve this problem?

If we don't

**Comment by matheusribeirozup** [comment]
The `useParentScroll` attribute for a first moment will be implemented **exclusively for the Web**, where the scenario of a list within a scrollable component is quite common, while for mobile it is preferably not used.

**Comment by Tiagoperes** [comment]
# E2E tests
Now that we have implemented the ListView, before releasing it, we must create its end-to-end tests using Cucumber.

## The application
The application we chose to test the feature is a page with 3 list views. All lists are based in a [small database of books](https://gist.github.com/Tiagoperes/e1e677e158433f7c5a6bf4ebf7947c5d) and their data sources will be retrieved from services in the BFF.

This is the page we are going to test:
![Page illustration](https://i.ibb.co/yN1vjrL/list-view-test.png)

### The first ListView (characters, pagination)
The first list view is a list view placed in the horizontal that uses a custom `iteratorName`. This is a simple list that, when initialized, loads the first page of the set of characters. The template shows the character name and the book and collection it comes from. This list should occupy all the width available and the height its content needs.

This list is also paginated and should be controlled by the buttons (prev/next) above it. The data source must be loaded via the backend service at `$bffUrl/book-database/characters?page=$page`. Moreover, since its a pagination and not an infinite scroll, the data source should be replaced when the page changes.

This list also has another feature, when it's scrolled to 100%, the text below it will alter from "status: unread" to "status:read". This is done so we can test the `onScrollEnd` event on a horizontal list. The threshold here must not be specified, i.e. it should use the default (100%).

### The second ListView (categories, nested)
This is actually 3 nested list-views. Its objective is to show every character for every book in every category. There's an onInit event for the top-most ListView (categories) and the middle ListView (books) that loads the data sources from the BFF.

The top-most list iterates over the list of categories. It is a vertical list with fixed height (307) and automatic width (occupies all the space available). Its data source comes from `$bffUrl/book-database/categories`.

The list in the middle iterates over the books of the current category. It is a horizontal list. It occupies all the width available and its height fits its content. The data source for this list comes from `$bffUrl/book-database/category/$categoryId`.

The deepest list iterates over the characters of the current book. It is a vertical list with no scroll that occupies as much space as its content needs. The data source for this list doesn't need to be loaded, the characters from a book comes in the field `characters` of the request made in the parent ListView (books).

In this ListView example it is very important to set the keys in the ListViews. We'll check the id assigning behavior in our tests:
- The top ListView must have the key `id`;
- the middle ListView must have the key `title`;
- the deepest ListView must not have a key.

It is also important to set some ids in the templates:
- The parent container in the top ListView must have the id `category`;
- The parent container in the middle ListView must have the id `book`;
- The text in the deepest ListView must have the id `character`.

### The third ListView (books, infinite scroll)
This list iterates over all books in the database. It is a vertical list that increases the height of the entire screen, i.e. it uses the scroll of the page instead of creating its own (`useParentScroll` is `true`).

This is an infinite scroll, i.e. it loads its content in the event `onScrollEnd`. The scroll threshold used for this list is 80%. To load the data source, a request should be made to `bffUrl/book-database/books?page=$page`. Moreover, since its an infinite scroll and not a pagination, the data source should be incremented when the page changes, never replaced.

### The book analytics
To be able to test the **onInit in a template** properly, we are going to create a custom action called `custom:bookAnalytics`. This action always receives a `source` and another property(ies) to identify the item loaded.

The idea here is that the developer wants to know which items are being viewed by the user. Every time an item is initialized, it will call the action `custom:bookAnalytics`.

- Every character in the first list view (characters) will call `custom:bookAnalytics` with `{ source: 'characters-list', character: characterName }`.
- Every category in the second list view (categories) will call `custom:bookAnalytics` with `{ source: 'categories-list', category: categoryName }`.
- Every book in the second list view (categories : books) will call `custom:bookAnalytics` with `{ source: 'categories-books-list', book: bookTitle }`.
- Every character in the second list view (categories : books : characters) will call `custom:bookAnalytics` with `{ source: 'categories-books-characters-list', character: characterName }`.
- Every book in the third list view (books) will call `custom:bookAnalytics` with `{ source: 'books-list', book: bookTitle }`.

In our tests this custom action can be just a mock we can observe when called.

## BFF services
The following end-points should be created in the BFF:

- `/book-database/characters?page=$page`: should bring every character with the properties `name`, `book` and `collection`. This result should be paginated, i.e. it should respect the structure `currentPage, totalPages, result`, where result is where the list of characters actually goes. There must be two pages only, the first with the first 34 characters and the second with the remaining 33.
- `/book-database/categories`: should bring every category/genre with its `id` and `name`.
- `/book-database/categories/$category`: should bring every book in the category/genre with id `$category`. Each book must have the properties `title`, `author` and `characters`.
- `/book-database/books?page=$page`: should bring every book with the properties `title`, `author`, `collection`, `bookNumber`, `genre` and `rating`. This result should be paginated, i.e. it should respect the structure `currentPage, totalPages, result`, where result is where the list of books actually goes. There must be 3 pages, each one with 15 books.

All these services must be based on [this json](https://gist.github.com/Tiagoperes/e1e677e158433f7c5a6bf4ebf7947c5d)

## Tests 
Because of all the scrolling involved in these tests, it is very important that we all use the same view port size when running the tests. The image used in the first section represents a view port size 480 x 720 (width x height).

### Tests for the first ListView (characters, pagination)

1. Check the rendering of the first page and the page indicator.
2. Test the process of going to page 2 from page 1.
3. Test the process of going to page 1 from page 2.
4. Check the rendering and the analytics of each character in page 1.
5. Check the rendering and the analytics of each character in page 2.
6. Check the behavior for the "read status" feature.
7. Check if the analytics action has not been called more times than it should have.

### Tests for the second ListView (categories, nested)

8. Check the rendering and the analytics of the list of categories.
9. Check the rendering and the analytics of each category and its list of books.
10. Check the rendering and the analytics of each book and its list of characters.
11. Check if the analytics action has not been called more times than it should have.

### Tests for the third ListView (books, infinite scroll)

12. Check the rendering and the analytics of the first pack of books.
13. Check if nothing happens by scrolling the view to a value under the threshold.
14. Check the rendering and the analytics of the second pack of books by scrolling the view to a value over the threshold.
15. Check if the action to add more books to the list is not called more than once when scrolling multiple times over the threshold before the request finishes.
16. Given the second pack is loaded already, check if nothing happens by scrolling the view to a value under the threshold.
17. Given the second pack is loaded already, check the rendering and the analytics of the third pack of books by scrolling the view to a value over the threshold.
18. Given all the data has loaded already, check if nothing happens by scrolling the view to a value over the threshold.
19. Given all the data has loaded already, check if every book has been correctly rendered and its analytics have been called.

**The `.feature` for all these test can be found [here](https://gist.github.com/Tiagoperes/75ab466704e2569a95c6c6390c996918).**
