### ISSUE TITLE
refactor: Log mechanism should be customisable and togglable

### ISSUE THREAD

**Issue by theffc** [ZupIT/beagle#246]
### Problem

Current implementation of Logging in iOS and Android are different, so we need to unify them.

### Acceptance Criteria

- Log mechanism should be a customisable behaviour, so a user could threat Log events in a completely different way. E.g: user wants to send all Log events to a analytics server

- Log mechanism should be easily enabled or disabled. E.g: user wants to disable log when in release mode, it must just disable a flag.

### Solution

- Make a configuration point for Log which uses an interface, and already provide a default implementation for it.
- Add a flag to the overall project configuration that will say if log will be triggered or not. It could be disabled by default
- Only forward Log events to the Log mechanism when flag is enabled. For this, we will need to make a proxy that knows our Flag, and will forward to the chosen Log mechanism.

------------

### Context

We thought about different Logging strategies like logging only on debug mode, or logging a more complete event description on debug and a more concise description on release, but this could be really tricky to implement for different contexts. So we are choosing the simpler path that will allow for great customisability.

Related Issues: #141, #152

**Comment by tuliopereirazup** [comment]
This is a suggestion for the Logging protocol.

Warning is to tell that something went wrong but it's not severe.
Error is when a crash occur or something similar.
Info is to log something that is not error but just informative, as example it's a http logging.

```kotlin
interface BeagleLogger {

    fun warning(message: String)

    fun error(message: String)

    fun error(message: String, throwable: Throwable)

    fun info(message: String)
}
```

**Comment by yandiaszup** [comment]
Since Beagle IOS its using swift 5, i think we can replace os.log for [SwiftLog](https://github.com/apple/swift-log/) as the logging API

**Comment by theffc** [comment]
@tuliopereirazup in iOS we have something slightly different. I suggested this approach because I think that the event "id" is more important than when it should be logged, so when we trigger them, we don't need to worry about those Log Levels

```swift
public class BeagleLogger {

    public func log(_ log: LogType) {
        os_log("\nBeagleSDK: %@", log: osLog(for: log), type: toOsLog(log.level), log.message)
    }
}

public protocol LogType {
    var category: String { get }
    var message: String { get }
    var level: LogLevel { get }
}

public enum LogLevel {
    case error
    case info
}
```
