### ISSUE TITLE
Create data response error

### ISSUE THREAD

**Issue by luisgustavozup** [ZupIT/beagle#257]
**Problem**
When I try to make a request in the HttpClientDefault class around the line 80, it falls in a exception like "java.io.EOFException". I supose that is when a data response is creating.

<img width="708" alt="Captura de Tela 2020-06-10 às 13 59 31" src="https://user-images.githubusercontent.com/59032921/84296638-b01ab700-ab22-11ea-96ca-85e9ef226640.png">

**Comment by lucka3s** [comment]
Could not reproduce
