### ISSUE TITLE
Add expression support to default components and actions

### ISSUE THREAD

**Issue by tuliopereirazup** [ZupIT/beagle#283]
### Describe the problem
We need to add Expression support to default components and actions.

### Expected behaviour

Here are all components that should be changed with only attributes that can now receive an Expression:

```kotlin
Button(
    val text: Expression<String>,
    val styleId: Expression<String>? = null,
)

Text(
    val text: Expression<String>,
    val styleId: Expression<String>? = null,
    val textColor: Expression<String>? = null,
    val alignment: Expression<TextAlignment>? = null,
)

Image(
    val url: Expression<String>,
    val mobileId: Expression<String>
)

TabItem(
    val title: Expression<String>? = null,
)

TabView(
    val styleId: Expression<String>? = null
)

WebView(
    private val url: Expression<String>
)

NavigationBar(
    val title: Expression<String>,
    val styleId: Expression<String>? = null
)

NavigationBarItem(
    val title: Expression<Int>,
    val imagePath: Expression<String>? = null
)

// Actions

AlertAction(
    val title: Expression<String>,
    val message: Expression<String>
)

ConfirmAction(
    val title: Expression<String>,
    val message: Expression<String>
)
```

**Comment by hernandazevedozup** [comment]
TODO LIST
- [ ] Button
- [ ] Text
- [ ] Image
- [ ] TabItem
- [ ] TabView
- [ ] WebView
- [ ] NavigationBar
- [ ] NavigationBarItem
- [ ] 
- [ ] AlertAction
- [ ] ConfirmAction

**Comment by victormr** [comment]
The following components are not going to be done:
NavigationBarItem;
TabItem;
NavigationBar(Title).

**Comment by victormr** [comment]
TODO LIST iOS

- [ ] Button

- [ ] Text

- [ ] Image

- [ ] TabView

- [ ] WebView

- [ ] NavigationBar

- [ ] AlertAction

- [ ] ConfirmAction

**Comment by uziasferreirazup** [comment]
@victormr and @hernandazevedozup this issue can be closed?
