### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by carlossteinzup** [ZupIT/beagle#301]
An update has been requested from one of our outside contributors requesting more info about Beagle and a clear path to documentation.

A README should be able to give general information about the application and concise orientation on how to get further and more detailed information.

**Comment by carlossteinzup** [comment]
The English revised documentation is being developed now and we will update all links as soon as it is available @uziasferreirazup

**Comment by carlossteinzup** [comment]
The README was refactored and the links were updated into linking the updated documentation. 
Since the English DOCs are not yet set the links are connecting to the Portuguese DOCs.
The text and info configuration was slightly changed and revised.

**Comment by TalbotGooday** [comment]
It is better to add links to the Portuguese documentation than to display the "Not found" page. It seems that the project is abandoned or something

**Comment by uziasferreirazup** [comment]
@TalbotGooday I really sorry about this experience, this week the team works very hard to improve the documentation and change to Portugues because this is most updated but will be changed to English next week and the links will be fixed.

**Comment by TalbotGooday** [comment]
@uziasferreirazup I meant that linking somewhere is better than linking nowhere) Anyway, thank you for your work 👍
