### ISSUE TITLE
Beagle is not rendering the Button properly on Android

### ISSUE THREAD

**Issue by pcmeurer** [ZupIT/beagle#379]
**Describe the problem**
Beagle is not rendering Button background on Android. See:
[beagle-bug-button.zip](https://github.com/ZupIT/beagle/files/4831600/beagle-bug-button.zip)

**Expected behavior**
When showing a Button the background should be drawn

**Comment by paulomeurerzup** [comment]
Acabei abrindo o issue com minha conta pessoal.. vida que segue

**Comment by paulomeurerzup** [comment]
<img width="308" alt="bug_demo" src="https://user-images.githubusercontent.com/66129650/85730745-4a0c6300-b6d0-11ea-86ad-75a9b9e5f102.png">

**Comment by matheusribeirozup** [comment]
Beagle on Android **does not map all styling attributes of all components**. In the case of the `Button`, to assign a background it is necessary in its style to assign the **background property**.
In your button style for example it is described as follows: `<style name="AppTheme.Button" parent="Widget.AppCompat.Button.Colored" />` the background property is not set.
Following is documentation informing how styling is done on Beagle components: https://docs.usebeagle.io/exemplos-e-tutoriais/estilizacao/android
