### ISSUE TITLE
Error when use components without bind

### ISSUE THREAD

**Issue by uziassantosferreira** [ZupIT/beagle#408]
**Describe the problem**
I using android declarative and trying to use button, but always show error in construct

![Screenshot from 2020-06-28 21-51-25](https://user-images.githubusercontent.com/9255894/85962957-d85f3e00-b989-11ea-9357-7f929a3e2cc1.png)

This happen because the second construct don't allow named parameters, but the named parameters it is a great feature

**Expected behavior**
The second construct works correct with named parameter

Suggestion: 

Stop using multiple construct in your data class

In this case the kotlin recommend using the operator invoke:

```
data class C(val a: Int) {
    companion object {
        //           v--- factory method
        operator fun invoke(value: String): C = C(value.toInt())
    }
}
```

**Comment by uziassantosferreira** [comment]
This errors persist in all components in android and backend too

**Comment by viniciusguardieirozup** [comment]
I tested this issue and it worked normally, the problem is with "style =", which should be "styleId ="
