### ISSUE TITLE
improve iOS CI workflow

### ISSUE THREAD

**Issue by theffc** [ZupIT/beagle#41]
To avoid creating a different issue for each item, I will aggregate here various improvements that can be made on the iOS workflow (_listed by priority_)

- [x] run SwiftLint on PR validation (add it to fastlane script), so we can avoid having too many errors and warnings in the future.
- [ ] add [SwiftInfo](https://github.com/rockbruno/SwiftInfo) to our project, so we can better visualize some important information.
- [ ] check if user is adding or changing some dependency and make this information more visible (this could also be done by just using `.codeowners` properly).
- [ ] check if there is any individual test that is taking more than 1 second. If so, automatically disapproves PR (only some superuser can approve) and leave a message (probably will need [Danger]() to do this).
- [ ] check if PR is big (maybe more than 15 files, or could check number of lines). If so, automatically increase the number of required reviewers.
- [ ] add some static code analysis to our project (can be SonarQube for example)

Obs: This is just a brainstorm, maybe some items would be too hard to implement, and so it doesn't really pay off to do them.

**Comment by dantes-git** [comment]
This will be closed for now, but we will continue to discuss ci improvements as the project evolves.
