### ISSUE TITLE
EPIC - Update PageView to have Context

### ISSUE THREAD

**Issue by theffc** [ZupIT/beagle#422]
## Description
Since we have launched Communication between Components (#54), we can now update the way PageView and PageIndicator communicates with each other by starting to use Context, Expressions, and Actions. This can, as well, help us identify some pain points when using those tools inside more complex components.

- [x] Web  https://github.com/ZupIT/beagle-web-components/issues/5
- [x] Android: #541  
- [X] iOS

**Comment by yandiaszup** [comment]
Branch created [refactor/page-view](https://github.com/ZupIT/beagle/tree/refactor/page-view)

**Comment by viniciusguardieirozup** [comment]
It is necessary to add a boolean attribute named as showArrow on declarative PageView, because this attribute will be used to indicate if the pageview arrows that are shown on the web should or not be visible.

**Comment by viniciusguardieirozup** [comment]
It is necessary change the eventName providede by the pageView.handleEvent to have the same behavior as the web
