### ISSUE TITLE
Beagle is not handling correctly view's onSaveInstanceState and onRestoreInstanceState

### ISSUE THREAD

**Issue by tuliopereirazup** [ZupIT/beagle#437]
### Describe the problem
Every Android view have the method that could be overridden called `onSaveInstanceState` to save the view state when a rotation occur and the `onRestoreInstanceState` to restore the view's state.
But this only works if the view has specified an ID, because Android System will look to every view and associate its state with the current view ID. The problem is that the rendering system do not generate an ID if the developer has not specified it and when the system tries to restore the saved state and the view does not have an ID, then the state is lost and the view is recreated with an empty state.

To reproduce this just render a TextInput, write some text on it and rotate the screen.

### Expected behaviour
We should generate and assign an unique ID to every view when the developer does not specify it.

To understand better, look this StackOverflow:
https://stackoverflow.com/questions/45658651/edittext-saved-the-value-after-device-rotation-automatically

**Comment by tuliopereirazup** [comment]
The same thing android does with IDs on views, we can do using Beagle Context Engine.
For now we are closing this issue.

**Comment by renan-lukas-iti** [comment]
Hey @tuliojuniorzup 
Is this issue expected to be solved anytime soon?

**Comment by tuliopereirazup** [comment]
Hi @renan-lukas-iti, we closed this issue in favor of the new context engine.
Context is like a ViewModel that holds view data and retain that in view recreations.

Context is present in version 1.0.0 but this fix to hold data on rotations were fixed on 1.0.2.

Basically every data that is needed to be retained in rotation like EditText, CheckBoxes, RadioButtons, etc., could be saved in context and recovered later using the context engine.

To understand how context works we have these two references:
https://docs.usebeagle.io/api/context
https://docs.usebeagle.io/resources/comunication-between-components-and-context

**Comment by renan-lukas-iti** [comment]
@tuliojuniorzup thank you for your quick reply
I have another question though: as far as I understand using the Context to store/retrieve data would mean that we need to map these Views on the client side, right? 
If so, is there a way to store/retrieve data without mapping these components? We didn't want to lose flexibility.
Would it make sense for the framework to provide a contract for saving/restoring data on each WidgetView?

**Comment by tuliopereirazup** [comment]
Regarding to store/retrieve, this is done by the context engine that is inside Beagle, not by your application. All you need to do is create the bindings for your widgets, map this bindings to your views and Beagle will handle everything for your.

But to exemplify a real use case, suppose your view has a text that should be changed using context. Them you should map this text attribute using the Bind class and observe the context changes to update the view text.
```kotlin
data class MyComponent(
    val text: Bind<String>
) : WidgetView() {

    override fun buildView(rootView: RootView): View {
        val view = MyView(rootView.getContext())
        observeBindChanges(rootView, text) { view.setText(it) }
        return view
    }
}
```

Them in your backend you could use the context like this:

```kotlin
Container(
   context = ContextData(
       id = "myContext",
       value = "MyComponent using an expression"
   ),
   children = listOf(
        MyComponent(valueOf("MyComponent using a static text")),
        MyComponent(expressionOf("@{myContext}")),
   )
)
```

And to make things a little better, you could use the action `SetContext` to manipulate the context and change its values, and every context changes your component will be notified.

**Comment by othiagosouto** [comment]
@tuliopereirazup so, this solution also could be applied to InputWidget? Lets work on this scenario: 

We got a `ComplexView` that the user already filled with some info and this value is not provided from our backend.

So, how we need to handle this? The value would be automatically stored through the value provided by the contract `getValue()` and beagle would save this value? is this ok for complex data such as `Serializable` or `Parcelable` class? 

suggestion: Would be way easier and android like if we provide such contract through as save and restore methods in `InputWidget`? 

```  
override fun onSaveInstanceState(outState: Bundle, view: View) {
        outState.putValue("SOME_KEY", view.getData())
        super.onSaveInstanceState(outState)
    }
```

```  
 override fun onRestoreInstanceState(savedInstanceState: Bundle, view: View) {
        val data = outState.getData("SOME_KEY")
        view.updateContent(data)
        super.onRestoreInstanceState(savedInstanceState)
    }
```

I think this approach would be way easier and will be better for android developers get use to beagle.

**Comment by tuliopereirazup** [comment]
Hi @othiagosouto, thanks for reply.
We do not document this case because this could add an extra effort to developer for every new view. 
But after version 1.0.1 is it possible to use `onSaveInstanceState` and `onRestoreInstanceState` inside your custom views, but we do not recommend using this approach because you need to take care of other platforms as well. Them the way we solved this problem for Android, iOS and Web is using context.
