### ISSUE TITLE
EPIC - Implement SimpleForm

### ISSUE THREAD

**Issue by diogooliveira-zup** [ZupIT/beagle#463]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Implement a way to Beagle trigger submitAction in SimpleForm through the event of a button inside of SimpleForm

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a SimpleForm and try to click on button inside one

## Expected Results
Trigger a Submit action in SimpleForm

## Code example, screenshot, or link to a repository:
Just try click in button inside of SimpleForm

- [x] Web V1.0
- [x] Android #532 
- [x] iOS

**Comment by tuliopereirazup** [comment]
Merged into 1.1
