### ISSUE TITLE
Improvement: registration of custom action and custom component

### ISSUE THREAD

**Issue by luisgustavozup** [ZupIT/beagle#481]
**Problem**
Create an annotation on iOS to register custom components and custom actions.
Android example that is already ready.

<img width="397" alt="Captura de Tela 2020-07-08 às 09 05 17" src="https://user-images.githubusercontent.com/59032921/86917098-f56ade00-c0fa-11ea-8d88-947b125a9149.png">

<img width="403" alt="Captura de Tela 2020-07-08 às 09 05 59" src="https://user-images.githubusercontent.com/59032921/86917104-f7cd3800-c0fa-11ea-8dc7-b4c60cf13517.png">

**Solution**
One possible solution is to create using Sourcery.

**Comment by theffc** [comment]
we will depreciate this due to a feeling that our users would probably not use Sourcery. If that changes, we can do that again.
