### ISSUE TITLE
Error in context

### ISSUE THREAD

**Issue by Nawan743** [ZupIT/beagle#484]
ERROR in node_modules/@zup-it/beagle-angular/components/beagle-markdown/beagle-markdown.component.d.ts(7,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by GuilhermeHdAS** [comment]
I also got this error, to fix it, I just give a random space in any file in the app folder, for example, I access the "app.module.ts" file, I give a random space anywhere, I delete and save it, without stop the application, it saves and compiles again, the second time it compiles it works.

Também obtive esse erro, para arrumá-lo, apenas dou um espaço aleatório em qualquer arquivo da pasta app, como por exemplo, acesso o arquivo "app.module.ts", dou um espaço aleatório em qualquer lugar, apago e salvo, sem parar a aplicação, ele salva e compila novamente, na segunda vez que compila dá certo.

ERROR in node_modules/@zup-it/beagle-angular/components/beagle-markdown/beagle-markdown.component.d.ts:7:9 - error TS1086: An accessor cannot be declared in an ambient context.

7     set text(inputText: string);
          ~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Failed to compile.

--------------------------------------------------------
After space in any file and compile again:
Após espaço em qualquer arquivo e compilar novamente:

$ npm run serve

> aprendizado-beagle@0.0.0 serve /home/socrates/aprendizadoBeagle
> npx beagle view-engine --npm && ng serve

 Done!  Beagle module files have been successfully generated at 
    "/home/socrates/aprendizadoBeagle/src/app"!

10% building 3/3 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to //index.html

chunk {main} main.js, main.js.map (main) 2 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 127 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 9.71 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 341 kB [initial] [rendered]
Date: 2020-07-09T13:55:25.368Z - Hash: d16e0f8b8d518b7f5b5e - Time: 11579ms

ERROR in node_modules/@zup-it/beagle-angular/components/beagle-markdown/beagle-markdown.component.d.ts:7:9 - error TS1086: An accessor cannot be declared in an ambient context.

7     set text(inputText: string);
          ~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Failed to compile.
ℹ ｢wdm｣: Compiling...
66% building 127/127 modules 0 active    
    ERROR in node_modules/@zup-it/beagle-angular/components/beagle-markdown/beagle-markdown.component.d.ts(7,9): error TS1086: An accessor cannot be declared in an ambient context.
    

Date: 2020-07-09T14:01:04.309Z - Hash: afd31764ff580f3723fc
2 unchanged chunks
chunk {main} main.js, main.js.map (main) 45.7 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 269 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.9 MB [initial] [rendered]
Time: 18115ms
ℹ ｢wdm｣: Compiled successfully.

**Comment by Tiagoperes** [comment]
Thank you for reporting, we'll look into it ASAP!

**Comment by Tiagoperes** [comment]
Can you please tell us which version of Angular you are using?

**Comment by Nawan743** [comment]
@angular/cli                      8.3.28 
typescript                        3.5.3

**Comment by GuilhermeHdAS** [comment]
Angular CLI: 8.3.28
typescript: 3.5.3

**Comment by Nawan743** [comment]
When i tried to use the new version of Angular, I had a error with "externalDecorators", so I do downgraded for version 8.3.28 and now I got this error

**Comment by pedropnaves** [comment]
> When i tried to use the new version of Angular, I had a error with "externalDecorators", so I do downgraded for version 8.3.28 and now I got this error

Can u detail the steps to reproduce this error ?

**Comment by Nawan743** [comment]
> > When i tried to use the new version of Angular, I had a error with "externalDecorators", so I do downgraded for version 8.3.28 and now I got this error
> 
> Can u detail the steps to reproduce this error ?

I tried to follow the steps in the documentation of Beagle, and when I went to run the project this error with "externalDecorators" occurred, so I downgraded my version of Angular for 8.3.28, and I ran again the project, in the first time that I ran this error with context is shown, so I have to give a space in anywhere in archive and save for compile

**Comment by Tiagoperes** [comment]
We just released [v1.0.1 of beagle-angular](https://www.npmjs.com/package/@zup-it/beagle-angular). Can you please yest it to see if the error is gone?

**Comment by Nawan743** [comment]
Oh, well. It's worked! Thx for help!

**Comment by GuilhermeHdAS** [comment]
> Acabamos de lançar a [v1.0.1 do beagle-angular](https://www.npmjs.com/package/@zup-it/beagle-angular) . Você pode testá-lo para ver se o erro desapareceu?

Muito obrigado, funcionou perfeitamente aqui também.
Thank you very much, it worked perfectly here too.
