### ISSUE TITLE
(Apply Style -> Flex) vs (Apply Flex)

### ISSUE THREAD

**Issue by gmarson** [ZupIT/beagle#496]
## Discussion
Today we can write the following code
```kotlin 
Container(
    children = listOf(
        Text("some text")
    )
).applyStyle(
    Style(flex = Flex(grow = 1.0))
).applyFlex(
    Flex(grow = 0.0)
)
```

1. What will happen here?
2. This is a desired behavior?

**Comment by LG95** [comment]
@gmarson today what happens is a Style with the second Flex instance, resulting in `container.style.flex.grow` being 0.0.

**Comment by ze12augusto** [comment]
This issue is being closed because we will continue with the current behavior
