### ISSUE TITLE
EPIC - Split Beagle components from core module

### ISSUE THREAD

**Issue by tuliopereirazup** [ZupIT/beagle#498]
## Description
We need to split components to another module but we cannot create a breaking change for this.

## Considerations: 
1. The new module will for now be shipped as a transitive dependency along with the core, but future release will break this.
2. Another consideration is WHAT to move to the new components module (organize a meeting to decide what do do?)

- [ ] Android #528 
- [ ] Backend #499 
- [ ] iOS #516 
- [ ] Web https://github.com/ZupIT/beagle-web-core/issues/82

**Comment by uziasferreirazup** [comment]
Currently we leave the modules totally independent and the schema will be responsible for guaranteeing the contract, I believe that this issue will not need action on it so I am closing.
