### ISSUE TITLE
EPIC - Integrated Tests

### ISSUE THREAD

**Issue by tuliopereirazup** [ZupIT/beagle#500]
## Description
We should create integrated tests for every component that we have.

# What is expected
1. Every platform should use the same contract (BFF) to use in every test cases.
2. Every test case that existe on BFF should exist on every platform.
3. For every test case we should consider two things: behaviour and snapshot.
3.1. Behaviour: the behaviour tests are expected to check every state, actions of components.
3.2. Snapshot: the snapshot tests are expected to check the rendering of components and its possible different states.
4. Create a new pipe to run this tests on CI.
5. Every test should be easily run on local machine.

- [ ] Web https://github.com/ZupIT/beagle-web-core/issues/245

**Comment by uziasferreirazup** [comment]
We finished the initial integration with cucumber, I'm finishing this epic because of that, if you fill up any more points we can discuss
