### ISSUE TITLE
EPIC - Improve our CI/CD pipe

### ISSUE THREAD

**Issue by tuliopereirazup** [ZupIT/beagle#501]
## Description
Some things need to be improved in our pipeline.

1. Deploy patches for each platform independently using Github Releases
2. Release from a specific branch
3. Split Android and Backend releases
4. Improve Github Actions Cache (https://github.com/marketplace/actions/cache)

## Tasks

- [x] Global: #485, #460, #459, #458, #456
- [x] Backend: #518, #519, #523, #525
- [x] iOS: #522, #580 
- [x] Web: https://github.com/ZupIT/beagle-web-react/issues/98 https://github.com/ZupIT/beagle-web-angular/issues/156 https://github.com/ZupIT/beagle-web-core/issues/178

**Comment by theffc** [comment]
For cache, backend and android already have this mechanism
