### ISSUE TITLE
EPIC - Update TabView to have Context

### ISSUE THREAD

**Issue by tuliopereirazup** [ZupIT/beagle#505]
## Description

Since we have launched Communication between Components (#54), we can now update TabView to simplify its implementation, and to allow new ways to use it on different use cases.

Ex1: use a TabView that the bar would be at the bottom, and the scroll of "pages" would be at the top

Ex2: when there is some change on current displayed "tab", I wanted to trigger an analytics event

## Possible Solution

- deprecate TabView and TabItem (and others related classes if needed)
- create a new TabBar component that will be just the view with a list of tabs.
  - current selected tab should be an expression
  - when some tab is selected, trigger an event
  - try to use it with PageView, to see if this new composition can be used instead of the old TabView
- update documentation accordingly

### Maybe problematic points

- TabView currently have some animations for its selected tab, and for the scroll of pages

- [x] Web https://github.com/ZupIT/beagle-web-components/issues/7
- [x] iOS:  try to see this as well #491 
- [x] Android #598

**Comment by yandiaszup** [comment]
Models: 
```
struct TabBar {
    public let children: [TabBarItem]
    public let styleId: String?
    public let currentTab: Expression<Int>?
    public let onTabSelection: [RawAction]?
}
```
```
public struct TabBarItem {
    public let icon: String?
    public let title: String?
}
```

**Comment by yandiaszup** [comment]
The idea its to use this TabBar component with PageView, communicating then with context and expressions to replicate TabView component behavior so we can deprecate it.

**Comment by yandiaszup** [comment]
### Solution: 
Refactor TabView to communicate with context, by adding 2 properties: 
`currentTab: Expression<Int>?` -> biding with context to change tabs every time currentTab changes
`onTabChange: [RawAction]?` -> list of actions that will be executed for every tab change inside TabView
Add 1 propertie to TabItem:
`onApear: [RawAction]?` -> list of actions that will be executed every time a specific tab apear on screen

### Structs:
```
struct TabView {
    public let children: [TabItem]
    public let styleId: String?
    public let context: Context?
    public let currentTab: Expression<Int>?
    public let onTabChange: [RawAction]?
}
```
```
struct TabItem {
    public let icon: String?
    public let title: String?
    public let child: RawComponent
    public let onApear: [RawAction]?
}
```

**Comment by yandiaszup** [comment]
The idea its to use this TabBar component with PageView, communicating then with context and expressions to replicate TabView component behavior so we can deprecate it.

**Comment by carolinegoncalveszup** [comment]
This change also request pageview contract to be changed.
For the expected behavior on the web we should add `showArrow` in pageview which is a boolean. This prop will be used to indicate if the pageview arrows that are shown on the web should or not be visible.

**Comment by carolinegoncalveszup** [comment]
For the tabview component we suggest:

`struct TabBar {
    public let items: [TabBarItem]
    public let styleId: String?
    public let currentTab: Expression<Int>?
    public let onTabSelection: [RawAction]?
}`

`public struct TabBarItem {
    public let icon: ImagePath?
    public let title: String?
}`

The tabItem array should not be children as it is not a ServerDrivenComponent, so we suggest `items` instead.
Another suggestion is to change the icon type to ImagePath, in which the _beagleImagePath_ must always be local
