### ISSUE TITLE
Flex values can't be "auto"

### ISSUE THREAD

**Issue by victorrabelozup** [ZupIT/beagle#533]
## Description

When setting layout properties like margins, if the value is of type `AUTO` it will work well only for Beagle Web.

## Steps To Reproduce
1. Create a Screen with the following json:
```json
{
    "_beagleComponent_": "beagle:text",
    "text": "Testing",
    "style": {
        "backgroundColor": "#FF2222",
        "size": {
            "width": {
                "value": 300,
                "type": "REAL"
            }
        },
        "margin": {
            "left": {
                "value": 0,
                "type": "AUTO"
            },
            "right": {
                "value": 0,
                "type": "AUTO"
            }
        }
    }
}
```

## Expected Results
- in web (the proper behavior):
![web](https://user-images.githubusercontent.com/7864241/87581537-7f90e480-c6af-11ea-857f-a2aa70bd0817.png)

- In iOS, the app will crash when debugging, and the value will just be ignored on production.
- In android, value will be ignored

## Code example, screenshot, or link to a repository:

- iOS exception when debugging:
`Exception    NSException *    "Not implemented"    0x000060000060e0d0`

**Comment by victorrabelozup** [comment]
This happens because the Yoga don't implement the `auto` value for some properties. This need to be documented as quickly as possible but ideally this error should not occur.

**Comment by theffc** [comment]
We discussed that it's not something critical and could be fixed latter. We will keep this open for further prioritization
