### ISSUE TITLE
Broken links in the README file

### ISSUE THREAD

**Issue by victorrabelozup** [ZupIT/beagle#563]
## Description
Some links to the documentation in the README.md file are broken(dos not exist).

## Steps To Reproduce
1. try to access the "Getting Started guide" link.

## Expected Results
Should open the "Getting Started guide" in the documentation

**Comment by victorrabelozup** [comment]
I want to suggest changing the current link from _Getting Started_ and _Learn the Basics_ to the "overview' and "main concepts" respectively.

**Comment by uziasferreirazup** [comment]
I don't recommend reference docs in language Portuguese.

**Comment by LG95** [comment]
@victorrabelozup I agree with _Getting Started_ linking to "overview", but _Learn the basics_ linking to "main concepts" I find awkward and prefer some either the playground or the current link.
