### ISSUE TITLE
iOS - try to solve the way we use YogaKit as a dependency both with CocoaPods and inside our repo

### ISSUE THREAD

**Issue by theffc** [ZupIT/beagle#566]
## Problems

- when using Cocoapods, users need to specify a dependency to a Yoga fork `pod 'YogaKit', :git => 'https://github.com/lucasaraujo/yoga.git'` which is owned by @lucasaraujo. Besides being weird, that can lead to inconsistency between versions of Yoga.

- We currently have all source code of Yoga inside our monorepo. Depending on *how* someone would use Beagle, this could lead to inconsistencies:
  - CocoaPods: users will get source code outside our monorepo
  - Carthage: users will get the exact source code from our monorepo
  - Internal usage: internal developers and CI use source code from monorepo

## Expected

The best solution was to rely on exactly the same source code and version of YogaKit for any of the methods described above. But a further investigation is needed to properly solve this issue

**Comment by dantes-git** [comment]
Solved with #1511 and #1484
