### ISSUE TITLE
EPIC - Conditional actions

### ISSUE THREAD

**Issue by Tiagoperes** [ZupIT/beagle#586]
**This epic supposes that the operations inside expressions are already implemented. i.e. it depends on the epic #503**

## Problem

As pointed out by @tarcisiogc, we need a way to execute actions based on a condition. For instance, suppose we have the user's age in a context and we want to call a request only if the user is over 21, otherwise we want to create an alert message.

We, currently, have no way of expressing this in our JSON. We can make conditions with the operations, but we can't execute an action based on the result of the condition.

In the next section, I present three solutions for this problem in order of complexity (less complex to more complex).

### 1. Add a new property to the base action
Besides the property `_beagleAction_`, all actions would also have the property `condition`. If `condition` resolves to `false`, it won't be executed. If `condition` is not specified or it resolves to `true` the action will be executed.

Example:
```json
{
  "_beagleComponent_": "beagle:container",
 "context": {
    "id": "user",
    "value": {
      "name": "Flynn Fairwind",
      "age": 40
    }
  },
  "children": [
    {
      "_beagleComponent_": "beagle:button",
      "text": "Buy some beer",
      "onPress": [
        {
          "_beagleAction_": "beagle:sendRequest",
          "condition": "@{gte(user.age, 21)}",
          "url": "/buy_some_bear",
          "method": "post"
        },
        {
          "_beagleAction_": "alert",
          "condition": "@{lt(user.age, 21)}",
          "message": "You can't buy beer yet!"
        }
      ]
    }
  ]
}
```

### 2. An action that makes conditions
We don't alter the base actions, instead, we create a new action: `beagle:condition`. `beagle:condition` has 3 parameters: `condition`, `onTrue` and `onFalse`. `condition` is mandatory, the other two aren't. When `condition` resolves to true, every action in `onTrue` is executed. When `condition` resolves to false, every action in `onFalse` is executed.

Example:
```json
{
  "_beagleComponent_": "beagle:container",
 "context": {
    "id": "user",
    "value": {
      "name": "Flynn Fairwind",
      "age": 40
    }
  },
  "children": [
    {
      "_beagleComponent_": "beagle:button",
      "text": "Buy some beer",
      "onPress": [
        {
          "_beagleAction_": "beagle:condition",
          "condition": "@{gte(user.age, 21)}",
          "onTrue": [
            {
              "_beagleAction_": "beagle:sendRequest",
               "url": "/buy_some_bear",
               "method": "post"
            }
          ],
          "onFalse": [
            {
              "_beagleAction_": "alert",
              "message": "You can't buy beer yet!"
            }
          ]
        }
      ]
    }
  ]
}
```

### 3. References to a context

We don't make any change to the actions themselves, instead we allow events to be associated to expressions, which would then be resolved to actions. With that, we could place the actions inside a context and just make references to them. 

Example:
```json
{
  "_beagleComponent_": "beagle:container",
 "context": {
    "id": "beer",
    "value": {
      "user": {
        "name": "Flynn Fairwind",
        "age": 40
      },
     "buy": {
        "_beagleAction_": "beagle:sendRequest",
        "url": "/buy_some_bear",
        "method": "post"
      },
      "alert": {
         "_beagleAction_": "alert",
          "message": "You can't buy beer yet!"
      }
  },
  "children": [
    {
      "_beagleComponent_": "beagle:button",
      "text": "Buy some beer",
      "onPress": "@{condition(gte(beer.user.age, 21), beer.buy, beer.alert)}"
    }
  ]
}
```

## Considerations
- The first and second solutions are very simple to implement
- The third solution is much more complex since none of the platforms are prepared to receive expressions in place of actions.
- Please, comment this issue to give your opinion about the solutions or to propose new ones.

**Comment by Tiagoperes** [comment]
We decided to implement the second approach (Daily of today).

**Comment by Tiagoperes** [comment]
Example in playground: https://beagle-playground-beta.netlify.app/#/demo/component-interaction/condional-action.json

**Comment by luisoliveirazup** [comment]
Conditional actions accept any type of data in "condition". If **condition == true**, run onTrue. In any other case, run onFalse. If **condition != True && condition != False && condition != Null**, show a warning saying something like "Conditional action. Boolean expected or null. Received: x"
