### ISSUE TITLE
Android DataBinding extensions for Beagle

### ISSUE THREAD

**Issue by bloderxd** [ZupIT/beagle#593]
# Use case

Android view creation style is changing gradually to a declarative paradigm, and many frameworks are supporting this changing being a Google official framework like DataBinding and Compose or a community framework like Beagle. But in cases that we follow an external and no official solution for that we lose some good things like Android Studio support, short learning curve, etc.

# Proposal

#### You can see a simple and WIP functional project [here](https://github.com/bloderxd/beagle-databinding) with more details

Thinking about that this issue proposes Google official declarative frameworks Beagle adapters starting with DataBinding, the goal here is to allow developers to develop a view on the same way that they develop today with xml / databinding and provide an extension to transform that view in a `Screen` type:

```kotlin
...
val binding: ActivityMainBinding = DataBindingUtil.inflate(layoutInflater, R.layout.activity_main, null, false)
val beagle: Screen = binding.toBeagle() // builds a Beagle `Screen` struct based on `activity_main.xml`
...
```

With that we can decrease a lot the Beagle learning curve since we're handling with xml layouts that are full supported by Google and provide to developers all advantages that Android Studio offers to DataBinding like layout previews.

**Comment by uziasferreirazup** [comment]
The Beagle team thanks you for your idea and your proposed solution! 
After careful evaluation, we came across a few points that would make it very difficult to implement across platforms, requiring massive support for each type of layout and their attributes, conversion to Flex (technology we use for positioning), etc. However, we do believe it has great potential as a tool of its own, building on Beagle, perhaps in the form of an Android Studio or Gradle plugin.

If you wish to continue with your idea, feel free to do so and count on us if you have any doubts!

**Comment by uziasferreirazup** [comment]
I will close this issue, but if you have any problems feel free to open another issue.
