### ISSUE TITLE
Context is not evaluating for PageView

### ISSUE THREAD

**Issue by viniciusguardieirozup** [ZupIT/beagle#607]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When use context inside PageView, the context is not being evaluated, this happen because the children is loaded asynchronous, and the fun evaluateContexts inside ContextDataManager already been called before the children was rendered 

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Get the JSON provided on https://beagle-playground.netlify.app/#/cloud/0306d41e4f8440c79f48e54fc1ed6c80/main.json
2. Check the Texts values is not setted

## Expected Results
It's expected the context be evaluated after the children was rendered

## Code example, screenshot, or link to a repository:
Android screen shoot
![Captura de tela de 2020-07-21 09-28-37](https://user-images.githubusercontent.com/58824112/88094598-3ab2f500-cb6a-11ea-9738-a80a45cbe6d8.png)
Result expected
![Captura de tela de 2020-07-21 15-53-12](https://user-images.githubusercontent.com/58824112/88094651-4d2d2e80-cb6a-11ea-8702-765efee979c2.png)

**Comment by tuliopereirazup** [comment]
Closed to merge related issues into one #684.
