### ISSUE TITLE
iOS - Dynamic Object error

### ISSUE THREAD

**Issue by luisgustavozup** [ZupIT/beagle#615]
## Description
When executing SendRequest with the context and json bellow, instead of the Dynamic Object returning it as an Array object, it returns as a String object.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
```kotlin
Screen(child: Container(
    children: [
        Text("@{test}", widgetProperties: WidgetProperties(
            style: Style(size: Size(
                width: UnitValue(value: 100, type: .percent),
                height: UnitValue(value: 100, type: .percent)
            ))
        )),
    ],
    context: Context(
        id: "test",
        value: ""
    ),
    onInit: [
        SendRequest(
            url: "https://run.mocky.io/v3/b7fe441a-392a-4409-b336-78affa956ed3",
            method: .get,
            onSuccess: [
                SetContext(
                    contextId: "test",
                    value: "@{onSuccess.data}"
                )
            ]
        )
    ]
))
```
## Expected Results 
Expected to return a array object

## Code example, screenshot, or link to a repository:
<img width="249" alt="Captura de Tela 2020-07-22 às 16 54 54" src="https://user-images.githubusercontent.com/59032921/88222294-22aba600-cc3c-11ea-83d6-0999aa4e6584.png">

**Comment by dantes-git** [comment]
Url provided in sample isn't working (invalid json), but the problem exists and can be verified with https://run.mocky.io/v3/b7fe441a-392a-4409-b336-78affa956ed3
