### ISSUE TITLE
EPIC - Stroke option in Container

### ISSUE THREAD

**Issue by josenetozup** [ZupIT/beagle#638]
## Description
Add stroke option in Container

Options: stroke color and stroke size

**Comment by josenetozup** [comment]
![Screenshot_1595937933](https://user-images.githubusercontent.com/46161684/88663714-65450680-d0b2-11ea-9ba4-2eab4d5eb230.png)
It would be an effect as in the attached image. What was done in this case is a container inside another

**Comment by yandiaszup** [comment]
I think we can add a appearance property to Style that will have all the appearance attributes like: 

- Corner Radius
- Shadow
- Stroke (color, width)
- Fill (background color)

**Comment by pedronaveszup** [comment]
> I think we can add a appearance property to Style that will have all appearance attributes like:
> 
> * Corner Radius
> * Shadow
> * Stroke (color, width)
> * Fill (background color)

I agree and as a suggestion I think we can add the styleid property to the container too

**Comment by uziasferreirazup** [comment]
add a new attribute in style with the name borderWidth and borderColor

**Comment by Tiagoperes** [comment]
Is the borderWidth attribute a number or a structure like `{ value: number, type: string }`?

**Comment by uziasferreirazup** [comment]
the width will follow the actual struct with `{ value: number, type: string }` in the backend this object it is called `UnitValue`

**Comment by Tiagoperes** [comment]
A percentage value for border-width is invalid for web, what does it mean in Android and iOS?

**Comment by uziasferreirazup** [comment]
`borderWidth: double`
