### ISSUE TITLE
Documentation the classes, fields, methods, etc..

### ISSUE THREAD

**Issue by uziasferreirazup** [ZupIT/beagle#64]
**Describe the problem**
It is difficult to understand the classes and the fields because they don't have a documentation when click to see detail of the class

**Expected behavior**
Add documentation to all the classes and fields

| Actual | Expected |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/63263091/80383073-7d21aa00-8879-11ea-8c64-bad53255c278.png" width="400" height="400" /> | <img src="https://user-images.githubusercontent.com/63263091/80383321-ce319e00-8879-11ea-88d6-c74b8cc42bb8.png" width="400" height="400" />  |

**Recomendation**
Use the [dokka](https://github.com/Kotlin/dokka) to generate your documentation.

**Android checklist**
- [x] Add documentation in classes

**iOS checklist**
- [ ]  Add documentation in classes

**Backend checklist**
- [x]  Add documentation in classes

**Comment by tuliopereirazup** [comment]
@theffc does we have someone on iOS dealing with this issue?

**Comment by theffc** [comment]
> @theffc does we have someone in iOS dealing with this issue?

No, not yet

**Comment by theffc** [comment]
will be tracked by #558
