### ISSUE TITLE
Custom component registration being lost

### ISSUE THREAD

**Issue by victorrabelozup** [ZupIT/beagle#656]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

The registration of a custom component is done by a calling a static method from `Beagle(Beagle.registerCustomComponent(...)`), this function uses the `dependencies` without the user know . So if he/she register their widgets them setup his/hers dependencies the widgets registration are lost and can't be recognized.

this works:
<img width="527" alt="Captura de Tela 2020-07-30 às 02 41 58" src="https://user-images.githubusercontent.com/68112545/88885102-43609680-d20e-11ea-8543-8935afa6dc4e.png">

this **doen't**:
<img width="537" alt="Captura de Tela 2020-07-30 às 02 41 06" src="https://user-images.githubusercontent.com/68112545/88885178-62f7bf00-d20e-11ea-8314-2b004532653c.png">

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Register custom widgets
2. Change the instance of the dependency in `Beagle.dependencies`

## Expected Results
The registration shouldn't be lost or the use of the dependency need to be more clear to the user to he/she can prevent this behavior.

**Comment by yandiaszup** [comment]
This error will occur not only with components, but with actions too.
