### ISSUE TITLE
iOS - Provide integration through Swift Package Manager

### ISSUE THREAD

**Issue by lucasfonsecazup** [ZupIT/beagle#692]
## Description

Today Beagle offers integrations through `Carthage` and `CocoaPods`, however with the growth in the use of the `SPM` (`Swift Package Manager`) by the community it would be interesting to offer integration through this dependency management tool.

## Acceptance Criteria

A developer being capable of using `SPM` to add Beagle to a Xcode project

**Comment by murilxaraujo** [comment]
Hello, I'm interested in solving this issue.
The Beagle iOS framework relies on facebook's YogaKit, which also does not have SMP support. I will be making a pr to the Yoga's repo adding support to SMP so we can declare it as a dependency on Beagle's Package.swift file and make it available through SPM.
