### ISSUE TITLE
Robolectric exeption java.lang.NullPointerException

### ISSUE THREAD

**Issue by hernandazevedozup** [ZupIT/beagle#698]
If we try to use robolectric to test beagle, the following exception occurs:

java.lang.NullPointerException related to SoLoader.

Maybe we can try something related to the method:
@BeforeClass
    public static void setup() {
        SoLoader.setInTestMode();
    }

**Comment by hernandazevedozup** [comment]
It works with the configuration below: 
Add these lines to your gradle file
`testImplementation "org.robolectric:robolectric:4.3.1"`
`testImplementation "com.facebook.soloader:soloader:0.8.2"`

`
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [Build.VERSION_CODES.P], manifest="AndroidManifest.xml")
class ExampleUnitTest {

    companion object {
        @BeforeClass
        @JvmStatic
        fun setup() {
            SoLoader.setInTestMode()
        }
    }

    private val beagleSetup = BeagleSetup()

    @Test
    fun robolectricTest1() {
        //It call your application onCreate, if your application initializes beagle, then it works
        buildActivity<MainActivity>(MainActivity::class.java).setup()
    }

    @Test
    fun robolectricTest2() {
        val application = RuntimeEnvironment.application;
        //Calls beagle init to check if Soloader exception occurs
        beagleSetup.init(application)
    }
}`

We can think of a better way to do this, like creating a method setInTestMode inside BeagleSetup class to do the             `SoLoader.setInTestMode()`
In that case the user of beagle dont need to add soloader dependency and just call BeagleSetup.setInTestMode() on @BeforeClass

**Comment by uziasferreirazup** [comment]
Another solution: create a library called the beagle-test and provide this method in this library.

**Comment by hernandazevedozup** [comment]
After the PR #704 we can now configure robolectric tests (no need to add the SoLoader dependency) with the following code below:
```
@BeforeClass
fun setup() {
BeagleSdk.setInTestMode()
}
```
```

@AfterClass 
fun teardown() {
BeagleSdk.deinitForTest()
}
```

**Comment by carlossteinzup** [comment]
Documented
https://docs.usebeagle.io/test/robolectric-configuration
