### ISSUE TITLE
Operations executed by the BFF responding with Actions

### ISSUE THREAD

**Issue by tuliopereirazup** [ZupIT/beagle#7]
### Problem
Beagle currently supports no direct means of expressing an operation that needs to be done by the BFF which will result in a change, commonly small, in the current view. Using the current actions, this would need to be expressed as a navigation to the operation's endpoint which will return the entire modified view.

### Example
Suppose a list view whose elements need to be removed when its trash button is clicked on. 

Currently, the trash button will have a navigation action to the endpoint of the removal operation and this operation will remove it and return basically the same screen, except without the element.

The desired change would be an Action that allows the server to send the operation's endpoint and this endpoint will respond with another element, likely an Action, that causes the list view to remove said element.

**Comment by LG95** [comment]
Part of #54.
