### ISSUE TITLE
Change the FormValidation name to FormValidationError

### ISSUE THREAD

**Issue by matheusribeirozup** [ZupIT/beagle#70]
**Problem description**
The `FormValidation` action takes care of displaying the errors returned by the api for a `Form`. However, her name does not match her function.

**Expected behavior**
A more intuitive name for this action would be `FormValidationError`, as it deals exclusively with errors.

**Development**
As this change has an impact for all Beagle projects, opening PR from the #74 and point to himself.

**Wait until #54, as it will likely already refactor all of form.**

**Comment by LG95** [comment]
Won't this change be done in #54?

**Comment by matheusribeirozup** [comment]
The `Form` component is going to be depreciated soon, so this issue no longer makes sense.
