### ISSUE TITLE
Toolbar title changes to app label if user changes system language with app open

### ISSUE THREAD

**Issue by vitor-ramos** [ZupIT/beagle#722]
## Description
After a user changes the system language, an already opened Beagle screen will show the app's label in the Toolbar instead of the screen's title.

## Steps To Reproduce

1. Open a Beagle screen with a navigation bar and a title (the title needs to be different from the app´s name);
2. Switch to system settings and change the system language;
3. Go back to your app and notice the Toolbar now shows the app's name instead of your defined title.

## Expected Results
The app should be showing the screen's title even after the user changed the system language.

## Screenrecord:
![Beagle screen title bugs on language change](https://user-images.githubusercontent.com/12222533/89696250-66b1d280-d8ed-11ea-9b80-a5d78a0c0418.gif)

**Comment by paulomeurerzup** [comment]
Not reproduced in master branch. This issue will be solved in 1.1 release.
