### ISSUE TITLE
Global context with cache problem when the global context value is changed on the screen

### ISSUE THREAD

**Issue by luisoliveirazup** [ZupIT/beagle#738]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
global context in value passed an object and changing the value of the global context to a new object it cannot update the new value due to the cache

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Follow the link for the use case: https://run.mocky.io/v3/3768663c-582e-4ed1-a237-f1cf62404d6e
2. Follow the example of the gif below, on the second screen when clicking the button the value navigationBar should update to Beagle navigationBar
![error_context_global](https://user-images.githubusercontent.com/59032818/89936821-982ae680-dbea-11ea-8517-5dfda8dfcbb0.gif)

## Expected Results
global context in value passed an object and changing the global context value to a new object it is able to update the new value.

## Code example, screenshot, or link to a repository:
Use case spoken in the text above

**Comment by tuliopereirazup** [comment]
Resolved with #764
