### ISSUE TITLE
EPIC - Improve analytics API

### ISSUE THREAD

**Issue by tuliopereirazup** [ZupIT/beagle#745]
### Description
We need some ways to improve the analytics API to get more info from what user is doing to take more inputs and consequently make decision based on data.

**Edit: Please, implement this feature according to [this](https://github.com/ZupIT/beagle/issues/745#issuecomment-717958929) comment of this issue.**

**Comment by Tiagoperes** [comment]
Link the original proposal for the Analytics 2.0: https://github.com/ZupIT/beagle-web-core/tree/specification/analytics2

As soon as I have sometime, I'll post here a summarized version in english.

**Comment by Tiagoperes** [comment]
Talk to Jefferson, Marson Carol from AutoCapture to align the changes for the Analytics.

**Comment by Tiagoperes** [comment]
# Disclaimer
The previous analytics must not be affected by any of these changes. We should keep the compatibility and, at least for now, nothing will be deprecated.

The two APIs must work without influencing one another.

# Configuration

The developer must be able to setup an `AnalyticsProvider`. Beagle will use this API to create analytics records according to its rendering process and actions.

The `AnalyticsProvider` is an API coded by the end-developer that must implement the following interface:

```typescript
interface AnalyticsConfig {
  /**
   * Default is true, when false no analytics will be generated by this system when a screen is
   * loaded.
   */
  enableScreenAnalytics?: boolean,
  /**
   * A map of actions allowed to create analytics records. By default no action creates records.
   * 
   * In this map, each key is a _beagleAction_, while the values are array of strings. The value
   * indicates which properties of the action will compose the analytics record. By default, only
   * the _beagleAction_ is sent as part of the record. If we want to send for instance, the url and
   * method of every "beagle:sendRequest", we must create the entry
   * { 'beagle:sendRequest': ['url', 'method'] }.
   */
  actions: Record<string, string[]>,
}

interface AnalyticsRecord {
  type: string,
  [key: string]: any,
}

interface AnalyticsProvider {
  /**
   * Returns the configuration for the analytics. In general, this configuration will be made
   * available by the backend. So, generally speaking, the first time this function is called, it
   * will make a request to an endpoint, store the configuration locally and return it. Every call
   * after the first one will just return the stored value.
   * 
   * Although this will be the general behavior, it is up to the end-developer to decide how the
   * configuration is retrieved, if he/she wants to use a configuration stored locally, there's
   * no problem.
   * 
   * @return a promise that resolves with the configuration
   */
  getConfig: () => Promise<AnalyticsConfig>,
  /**
   * Starts a session for the analytics. In general, most analytics services require you to start
   * a session with basic user data before starting to create records. This function must start
   * the session and store every key necessary to create the records themselves.
   * 
   * This function will be called as soon as Beagle starts.
   * 
   * @return a promise that resolves when the session is fully started
   */
  startSession: () => Promise<void>,
  /**
   * Calls the analytics service to create a new Record. Most analytics services will require
   * the keys obtained in `startSession` to be sent here.
   * 
   * This function will be called every time Beagle needs to create a record. If you don't want
   * to send one request for each analytics generated by Beagle, it is a good idea to implement a
   * batch mechanism within this function.
   * 
   * @param record the record to create
   */
  createRecord: (record: AnalyticsRecord) => void,
}
```

> Attention: in Beagle-WEB, we use promises to do the async operations. Use whatever works best for the platform you're working on.

We, as the developers of Beagle, will not implement any of these methods. We will only use them. The responsibility to implement these functions is of the end-developer, i.e., the person who uses Beagle to build an application.

Beagle must provide a way to register the `AnalyticsProvider`. It can be an annotation, a XML, a configuration option, etc. Each platform must choose the best way to do this according to its scenario. In the case of Beagle-WEB we must create a new configuration option:

```typescript
interface BeagleConfig {
  // ...
  analyticsProvider?: AnalyticsProvider,
}
```

The `analyticsProvider` is optional. If no `analyticsProvider` is registered, no analytics will be generated through this system.

# Action: inline analytics configuration

The configuration returned by `analyticsProvider.getConfig()` can be overwritten by action-specific configurations. The `BeagleAction` interface must now be augmented with the property `analytics`:

```typescript
interface BeagleAction {
  _beagleAction_: string,
  analytics?: {
    /**
     * When false, no analytics record will be created for this action. When true, a record will be
     * created. No matter what `analyticsProvider.getConfig()` says.
     * 
     * When not specified, the `analyticsProvider.getConfig()` is used.
     */
    enable?: boolean,
    /**
     * The analytics record will expose all attributes of the action present in this array, no
     * matter what `analyticsProvider.getConfig()` says.
     */
    attributes?: string[],
    /**
     * Specifies additional data to be sent in the analytics record.
     */
    additionalEntries?: Record<string, any>,
  }
}
```

# Starting an analytics session

As soon as Beagle starts, if an `analyticsProvider` is set, we must call `analyticsProvider.startSession()`. The Analytics provider itself is the one responsible to know how to start an analytics session with the application's service of choice. Beagle is only responsible for calling `startSession()`.

# Creating screen records

Every time a screen is rendered, Beagle must verify if it should generate an analytics record.

An analytics record should be generated if the `analyticsProvider` exists and if `analyticsProvider.getConfig()` resolves to a configuration where `enableScreenAnalytics` is not false.

If we should generate an analytics record, we must first create the record:

```typescript
const record: AnalyticsRecord = {
  type: 'screen',
  platform: 'web-react',
  url: 'my-url', // for remote routes
  screenId: 'screenId', // for local routes
}
```

And then, we have to send the record:

```typescript
analyticsProvider.createRecord(record)
```

# Creating records for actions

Every time an action is executed, we must verify if it should generate an analytics record.

Considering the executed action as `action`:

An analytics record should be generated if `analyticsProvider` exists **and**:
- if `action.analytics.enable` is `true`; **or**;
- if `action.analytics.enable` is **not** `false`; and;
  - if `analyticsProvider.getConfig()` resolves to a configuration where the map `actions` has the key `action._beagleAction_`.

i.e.

```typescript
const isActionDisabled = action.analytics && action.analytics.enable === false
const isActionEnabled = action.analytics && action.analytics.enable === true
const config = await analyticsProvider.getConfig()
const isActionEnabledInConfig = config.actions[action._beagleAction_]

const shouldGenerateAnalytics = analyticsProvider && (isActionEnabled || (!isActionDisabled && isActionEnabledInConfig))
```

If we should generate the analytics record, then, we must create the record.

The following properties should be added to the record independently of the configuration:

```typescript
const record: AnalyticsRecord = {
  type: 'action',
  platform: 'web-react',
  screen: '/step1', // url or screenId of the current view
  event: 'onPress', // name of the event that triggered this action
  component: { // data about the component who triggered this action
    type: 'beagle:button', // the value of _beagleComponent_
    id: 'btn-next', // id of the component
    position: { 'x': 158, 'y': 350 }, // position in the screen where the components is located (if possible),
    xPath: '//html/body/app-root/beagle-remote-view/app-container/app-form/form/app-container/app-button[2]/button', // xPath in html (only for web)
  },
  beagleAction: 'pushView', // the _beagleAction_ of this action
}
```

If some information makes sense only for a single platform, we can include it here, there's no problem, see the `xPath` for instance, it's only relevant for web applications.

### Attributes of an action

As it can be seen, we are only sending the name of the action. We should be able to send the entire action if the end-developer wants to. To check which attributes of the action we should send, we must check both the configuration and the action itself.

First, check, the action: if it has `analytics.attributes`, for each `attribute` in `analytics.attributes`, add the `attribute` and its value to the record. For instance, suppose, the executed action had the following structure:

```json
{
  "_beagleAction_": "pushView",
  "route": {
    "url": "my-url.com",
    "shouldPrefetch": true,
    "fallback": { 
      // ...
     }
  },
  "analytics": {
    "attributes": ["route.url", "route.shouldPrefetch"]
  }
}
```

We would then alter the record so it becomes:

```typescript
const record: AnalyticsRecord = {
  // ...
  route: {
    url: 'my-url.com',
    shouldPrefetch: true,
  },
}
```

**If the action doesn't have `analytics.attributes`**, we should check the configuration. Call `analyticsProvider.getConfig()`, wait for the configuration to be resolved and then check if the config has the map `actions`. If it has, check if this map has the key `action._beagleAction_`. If the key exists, you should use its value, which is an array of strings, just like the previous step. For each `attribute` in  the array, add the `attribute` and its value in the action to the record.

### Additional entries for an action analytics record

The developer must be able to generate additional record entries from the backend. e.g. when a button is pressed, besides the action parameters and the default data of an analytics record, the backend could also want to send additional information like `buttonDescription`, `navigationHistory`, etc.

To send arbitrary additional information in an analytics record from the backend, the action must specify the attribute `analytics.additionalEntries`.

If the map `analytics.additionalEntries` exists in the action, we must augment the record with every <key, value> pair in the map. For instance, suppose the following action:

```json
{
  "_beagleAction_": "pushView",
  // ...
  "analytics": {
    // ...
    "additionalEntries": {
      "buttonDescription": "when clicked, this button sends the user to the profile view",
      "navigationHistory": "signIn > home > account"
    }
  }
}
```

We would then alter the record so it becomes:

```typescript
const record: AnalyticsRecord = {
  // ...
  buttonDescription: 'when clicked, this button sends the user to the profile view',
  navigationHistory: 'signIn > home > account',
}
```

### Sending the analytics record

After creating the analytics record, we must send it using the `analyticsProvider` API.

```typescript
analyticsProvider.createRecord(record)
```

**Comment by Tiagoperes** [comment]
Incremental changes according to the daily of 11/24:

1. We call `getConfig()` and `startSession()` of the `AnalyticsProvider` at the start. Both methods are asynchronous and we don't create any record until both are completed. When an analytics record arrive before these two methods are finished, they are queued. In some rare cases, one of these methods might never finish, which could make this queue grow indefinitely. To solve this problem we are going to establish a limit to the number of records this queue can hold.

2. Include an optional method in the `AnalyticsProvider` interface: `getMaximumItemsInQueue`. When not specified, the maximum number of items in the queue will be 100. This is the queue to hold the records while `getConfig()` and `startSession()` are not finished.

3. When the queue reaches the maximum number of items, the following warning should be printed: `${maxItems} analytics records are queued and waiting for the initial configuration of the AnalyticsProvider to conclude. This is probably an error within your analytics provider. Why are getConfig() and startSession() not done yet? From now on, some analytics records will be lost. If you need to increase the maximum number of items the queue can support, implement getMaximumItemsInQueue() in your AnalyticsProvider.`

4. When a new record item is to be queued, but the queue is already at max size, remove the oldest item before adding the new one.

**Comment by Tiagoperes** [comment]
Meeting of 01/19/2021

```
createActionRecord {
  config = getConfig()
  if (config == null) return enqueue(action)
  if (!isEmptyQueueThreadStarted) startEmptyQueueThread()
  record = createRecord(action, config)
  provider.createRecord(record)
}

interface AnalyticsProvider {
  getConfig: () => (AnalyticsConfig | null),
  getMaximumItemsInQueue?: () => number,
  createRecord: (record: AnalyticsRecord) => void,
}
```

**Comment by Tiagoperes** [comment]
Analytics types have been modified:

Types:

```typescript
interface AnalyticsRecord {
  type: 'screen' | 'action',
  platform: string,
  timestamp: number,
  screen: string, // url or screenId of the current view
}

interface AnalyticsActionRecord extends AnalyticsRecord {
  beagleAction: string,
  event: string,
  attributes: Record<string, any>,
  additionalEntries: Record<string, any>,
  component: {
    type: string,
	  id: string,
	  xPath: string,
  },
}
```

Exemplos: 

```typescript
const screenRecord: AnalyticsRecord = {
  type: 'screen',
  platform: 'web-react',
  timestamp: 1284545454545,
  screen: '/step1', // url or screenId of the current view
}

const actionRecord: AnalyticsActionRecord = {
  type: 'action',
  platform: 'web-react',
  timestamp: 1284545454545,
  screen: '/step1', // url or screenId of the current view
  event: 'onPress', // name of the event that triggered this action
  component: { // data about the component who triggered this action
    type: 'beagle:button', // the value of _beagleComponent_
    id: 'btn-next', // id of the component
    position: { 'x': 158, 'y': 350 }, // position in the screen where the components is located (if possible),
    xPath: '//html/body/app-root/beagle-remote-view/app-container/app-form/form/app-container/app-button[2]/button', // xPath in html (only for web)
  },
  beagleAction: 'beagle:pushView', // the _beagleAction_ of this action
  attributes: {
    // all whitelisted attributes of the action
  },
  additionalEntries: {
    // all additionalEntries declared in the action
  }
}
```
