### ISSUE TITLE
iOS - release is taking too long with CocoaPods

### ISSUE THREAD

**Issue by theffc** [ZupIT/beagle#756]
### Problem

Since we introduced `--synchronous` in #705, that solved the problem of eventual consistency, but it made our release process [too slow](https://github.com/ZupIT/beagle/runs/966643405?check_suite_focus=true)

```md
+------+---------------------------------------+-------------+
|                      fastlane summary                      |
+------+---------------------------------------+-------------+
| Step | Action                                | Time (in s) |
+------+---------------------------------------+-------------+
| 1    | git fetch                             | 4           |
| 2    | git checkout master                   | 4           |
| 3    | last_git_tag                          | 0           |
| 4    | fastlane android deploy_to_production | 1164        |
| 5    | fastlane backend deploy_to_production | 468         |
| 6    | fastlane ios release                  | 2247        | <-----
| 7    | Switch to release_notes lane          | 0           |
| 8    | Switch to lastExpectedVersion lane    | 0           |
| 9    | git show-ref -s 1.0.0                 | 0           |
| 10   | conventional_changelog                | 0           |
| 11   | bash ./delete_release.sh              | 2           |
| 12   | set_github_release                    | 0           |
+------+---------------------------------------+-------------+
```

That probably happened because the way `--synchronous` achieve its results, which seems to be by actually cloning the CocoaPods main spec (and that's a huge git repo with like 1GB), instead of using trunk CDN.

### Possible Solution

We still don't know how to properly solve this, we need proper investigation of this issue. Maybe some ways would be to:

- see if there is other parameters that could be passed besides `--synchronous` to see if trunk would work
- check whether the problem of eventual consistency still happens on CDN trunk
- maybe implement by hand some kind of non-blocking code on our CI that would still use CDN trunk but would be pulling from time to time to check wether the dependent pod was actually updated.
- maybe do some kind of caching of the CocoaPods main spec, so we could keep this solution unchanged and just solve by using cache (but this option doesn't seem appropriate)

### Reference

this is the [PR where `--synchronous` was developed inside CocoaPods](https://github.com/CocoaPods/cocoapods-trunk/pull/147)

**Comment by dantes-git** [comment]
Since we removed the `BeagleSchema` module on iOS, we no longer use the `--synchronous` flag on the release process
