### ISSUE TITLE
Check another library to use in place of Glide.

### ISSUE THREAD

**Issue by tuliopereirazup** [ZupIT/beagle#768]
### Description
Actually we are using Glide to fetch remote images, but this library is big and we are using a simple piece and not the whole library.

An alternative is to implement our own or use another tiny library.

**Comment by uziasferreirazup** [comment]
Picasso

**Comment by victormoraeszup** [comment]
Suggestion: Coil -> https://github.com/coil-kt/coil

**Comment by uziasferreirazup** [comment]
coil has the same problem, the size of the library it is big.

**Comment by uziasferreirazup** [comment]
the best solution is the beagle does the request and if the developer wants to use something more specific, they can create your custom widget with your respective library.

**Comment by victormoraeszup** [comment]
I agree with you
