### ISSUE TITLE
A way to show/hide components in the tree

### ISSUE THREAD

**Issue by Tiagoperes** [ZupIT/beagle#794]
## Use case
Every major rendering framework has an option to show/hide elements according to a variable. This is a very useful feature in any UI. There should be a way to this in Beagle.

In Beagle web, when we need to do this, we alter the option `display` in `style` according to a value in the context. But, we know this is not supported in Android and iOS, so we didn't document it and every time someone asks how to do this with Beagle, we say it doesn't work out of the box and we tell the user he needs to create a custom component.

How should we implement this feature in a way every platform supports it for every component, without the need of further coding by the developer?

**Should we just show/hide an element, keeping it in the UI tree? Or should we destroy/build the element, removing it from the tree?**

If we just show/hide the element, a text input with some text inputted, for instance, would be hidden and, when showed, it would be back with its content, 'cause, in truth, it hasn't been destroyed. This has better performance because we don't need to rebuild the components, and the state will always be kept.

If instead of showing/hiding we destroy/build the component, the text input would be re-created without any text inside. The advantage of destroying/building is that we'd never try to build a portion of the tree if we are not ready to build it yet. Let's say we have panel with all the data of a client and this data comes from a backend service. We could tell beagle not to render this panel until the request finishes and the client data is available. This would avoid unnecessary renders and null pointers. By only showing/hide, the panel would be rendered anyway, it would just not be visible.

Should we have ways to do both?

## Proposal
If we just need to show/hide, i think the `display` option under `style` is fine. We just need to make it bindable in both iOS and Android.

If we also need a way to tell if a branch of the tree should be rendered or not, then I think we should have a new meta-property, along-side `style`. Maybe `_shouldRender_`?

- [ ] Android: #1063

**Comment by Tiagoperes** [comment]
We decided to implement only showing and hiding the component, but leaving it in the tree.

`display: 'NONE'` will hide the component and the space it would otherwise occupy.

**Comment by Tiagoperes** [comment]
- Document this feature
- Create an integration test

**Comment by Tiagoperes** [comment]
WEB: this should be working already, since "display: none" is native from css.

**Comment by uziasferreirazup** [comment]
the documentation about this attribute: https://docs.usebeagle.io/resources/component-layout/display.
I think don't need to update
