### ISSUE TITLE
Incorrectly deserializes an integer into a double-value

### ISSUE THREAD

**Issue by victormoraeszup** [ZupIT/beagle#795]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
The api http://demo1884512.mockable.io/beagleissue returns the type of id int, but the beagle in the response transform to double-value.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Click Button "Request Server"
2. Waiting for response

## Expected Results
20 int, not 20.0 double

## Code example, screenshot, or link to a repository:
`Container(
            context = ContextData(id = "responseServer", value = ""),
            children = listOf(
                TextInput(value = expressionOf("@{responseServer.id}")),
                Button("Request Server", styleId = "primaryButton", onPress = listOf(
                    SendRequest(
                        url = "http://demo1884512.mockable.io/beagleissue",
                        method = RequestActionMethod.GET,
                        onSuccess = listOf(
                            SetContext(contextId = "responseServer", value = "@{onSuccess.data}")
                        ))
                ))
            )
        )`

**Comment by victormoraeszup** [comment]
Moshi issue: https://github.com/square/moshi/issues/1144

**Comment by uziasferreirazup** [comment]
@victormoraeszup after your refactor I tested and the value continues showing incorrect x.x

**Comment by uziasferreirazup** [comment]
Code I used to test:

```
object PageViewScreenBuilder : ScreenBuilder {
    override fun build() = Screen(
        navigationBar = NavigationBar(
            "Beagle PageView",
            showBackButton = true,
            navigationBarItems = listOf(
                NavigationBarItem(
                    text = "",
                    image = Local.justMobile("informationImage"),
                    action = Alert(
                        title = "PageView",
                        message = "This component is a specialized container " +
                            "to hold pages (views) that may be swiped.",
                        labelOk = "OK"
                    )
                )
            )
        ),
        child = Container(
            children = listOf(
                Text(
                    "Pagina atual @{contexto}"
                ),
                Button(
                    "ir página 3",
                    onPress = listOf(SetContext("context", 2))
                ),
                PageView(
                    children = (1..3).map {
                        Text("Page $it", alignment = TextAlignment.CENTER).applyFlex(
                            Flex(
                                alignSelf = AlignSelf.CENTER,
                                grow = 1.0
                            )
                        )
                    },
                    onPageChange = listOf(SetContext("context", "@{onPageChange}")),
                    currentPage = expressionOf("@{context}")
                ),
                PageIndicator(
                    numberOfPages = 3,
                    selectedColor = BLACK,
                    unselectedColor = LIGHT_GREY,
                    currentPage = expressionOf("@{context}")
                )
            ),
            context = ContextData("context", 0)
        ).applyFlex(Flex(grow = 1.0))
    )
}
```

Result when I open the screen:
![Screenshot_1598961131](https://user-images.githubusercontent.com/63263091/91846219-21e93500-ec28-11ea-89ac-371459eb5e62.png)

But if I go to page one and return to page zero the result it is correct:
![Screenshot_1598961137](https://user-images.githubusercontent.com/63263091/91846494-33324180-ec28-11ea-95e7-15074b58cdc0.png)

**Comment by victormoraeszup** [comment]
hmm, I will check @uziasferreirazup

**Comment by victormoraeszup** [comment]
new issue to the context problem: https://github.com/ZupIT/beagle/pull/865
