### ISSUE TITLE
DSL doesn't support directly passing values to bindable fields

### ISSUE THREAD

**Issue by uziasferreirazup** [ZupIT/beagle#797]
## Description
When I try to use the DSL provided by Beagle I can't use attributes without `Bind`.

## Steps To Reproduce

<img width="299" alt="Screen Shot 2020-08-19 at 13 35 03" src="https://user-images.githubusercontent.com/63263091/90672360-63dba980-e22c-11ea-940a-882164df87df.png">

## Expected Results

the code above can be compile.

**Comment by LG95** [comment]
I believe we need to discuss this problem, as getting the above code to compile has negative consequences, since the field will have to stop being typed as a `Bind`

**Comment by uziasferreirazup** [comment]
I think the negative consequences it is the wrong term, you can say you can't do this in DSL mode today,  because I can do this instance object without use DSL if it is a negative consequence you need to block this behavior in the object too.

**Comment by uziasferreirazup** [comment]
dsl was deprecated because this I close this issue.
