### ISSUE TITLE
CustomAction com Widget

### ISSUE THREAD

**Issue by mizoguc** [ZupIT/beagle#810]
Criação de uma Custom Action com Widget interno.

## Description
Ao criar uma custom Action com um widget como atributo.

Atualmente para obter uma view do widget (ServerDrivenComponent) é necessário instanciar uma BeagleScreenViewController para então obter a view.

Neste cenário quando obtenho a view não é possível obter os dimensionamentos que seria do componente renderizado.

A ViewController nativa está trabalhando com as views de autoLayout e o Widget por renderizar apenas com o Flex não disponibiliza os dimensionamentos finais a view renderizada.

## Steps To Reproduce

1. Criação de uma customAction com widget(ServerDrivenComponent), não customizado.
2. gerar a view com o widget e atribuir esta view a uma ViewController
3 ViewController deve exibir essa view com a altura dinâmica da view gerada.

## Expected Results
View aparece  com altura zerada.

**Comment by theffc** [comment]
Obrigado @mizoguc pelo feedback nessa issue e tb por as outras conversas que tivemos aí ao longo da semana. Acredito que conseguimos entender melhor o problema, e tentaremos atacar alguns pontos para permitir que esse caso de uso seja atendido.

Para isso, precisaremos abordar 2 pontos principais:

1. Interoperabilidade entre Yoga e AutoLayout
    Para que seja mais fácil incluir os componentes Beagle em telas nativas complexas que utilizam o AutoLayout, precisaremos criar e expor uma UIView customizada que já lide de forma mais automática com essa comunicação entre os 2 "frameworks". Para esse problema a completude é desafiadora, por se tratar de 2 sistemas de posicionamento de views que funcionam de formas diferentes, mas acreditamos ser possível chegarmos numa solução que atenderia os casos principais.

2. Desacoplar o Widget (UIView) da BeagleScreenViewController
    Hoje a view que criamos a partir de um componente necessita do nosso UIViewController customizado para que os comportamentos mais complexos do Beagle funcionem da forma devida. Mas entendemos que muitas vezes ter que lidar com o UIViewController não faz tanto sentido para alguns casos de uso. No entanto, o desacoplamento total será uma tarefa bem desafiadora, pois o BeagleScreenViewController é uma peça bem importante na nossa arquitetura atual e precisaríamos fazer algumas refatorações em outros pontos.

Esses pontos são independentes e podemos atacá-los simultaneamente, mas para atender o caso de uso de vocês por completo, realmente seria necessário que os 2 estivessem solucionados. E infelizmente são ajustes que impactam o projeto como um todo, e por isso precisamos avançar com certa cautela para ter certeza de que estamos indo pro caminho correto.

Fechamos a nossa release 1.2.0, e vamos trabalhar nos pontos citados com bastante prioriade para chegarmos numa solução tecnicamente viável. Assim que formos avançando nos pontos, conseguiremos dar uma melhor visão sobre tempo, riscos, e tradeoffs envolvidos.

Fique à vontade aí para tirar outras dúvidas e estamos bem abertos a sugestões, qualquer coisa pode chamar por aqui ou por outros canais.

**Comment by hernandazevedozup** [comment]
Closed on version https://github.com/ZupIT/beagle/releases/tag/1.2.2-iOS
