### ISSUE TITLE
SwiftUI support?

### ISSUE THREAD

**Issue by roip890** [ZupIT/beagle#816]
Hi,

There is a way to work with beagle with SwiftUI Views?
There is a way to make a custom widget and update the context whenever I want?

For example, if I want to build my own form widgets, like multi-selector, image upload, etc. and I need to update the context because they are part of the context.

Thanks

**Comment by theffc** [comment]
About SwiftUI, we don't have that support yet. But it's definitely something we want to tackle in the future. We just have some other priorities right now.

About the other question regarding `context`, are you talking about the beagle concept that works for communicating between components? If so, yes you can have custom widgets that also use that concept.

E.g:

```swift
struct MyWidget: Widget {
    let someValue: Expression<String>
    let onSomeEvent: [RawAction]?
}
```

Here, you can use `someValue` to get the most updated value, and you could use `onSomeEvent` to trigger state changes in the context. That way, you custom component only needs to `execute` the `onSomeEvent` when necessary. You can see an example for that in our implementation of `Button` (a more complex scenario can be seen in `TabBar` as well).

**Comment by dantes-git** [comment]
Closed because we are already planning to support SwiftUI in a major release. (Similar issue #120)
