### ISSUE TITLE
[Draft] EPIC - improve Cache Mechanism

### ISSUE THREAD

**Issue by theffc** [ZupIT/beagle#825]
### Summary

We propose a new parameter to our Cache Mechanism that will change how we interpret `beagle-hash` and `maxAge`, and make it easier to understand which type of content we are trying to handle.

We were not being able to handle a really common use case in which the content is dynamic and so it needs to always be checked, but if there is a network error, we could fallback to our valid cache.

### Background - Types of Content

These seems a reasonable differentiation of the most frequent types of content for Beagle applications:

1) Dynamic Content: a content that uses data which can be updated frequently. Whenever it's viable, we would want to get an updated data, but there is no problem of showing a somewhat outdated data here.
   - this is a very common use case and we are trying to make this easier to do with this proposal
   - it could make sense to show cached data _as new data is being requested_

2) Static Content: some content that doesn't change frequently, and would change just after some specific event.
   - for this content, it would be good if server could say when things have changed, so it can invalidate cache for the next request

3) Dynamic Sensitive Content: this type of content changes frequently, and showing outdated data for users can lead to problems, thus updates need to be propagated really quickly (live if possible)
   - it seems like cache is a concept that doesn't really makes sense here.

4) Big Content or Network Perfomance: in some scenarios that uses a lot of data, we would want to minimize network payloads, so we could avoid using too much bandwidth from users. This could be used in conjuction with other types of content.
   - we tried to handle this with `beagle-hash` but it didn't work, see current problems for more information.

### Current Problems

Our current implementation of cache works by defining some parameters for each content identified by a URL. We have 2 parameters `beagle-hash` and `maxAge` which are used as http headers. They work for some really specific cases, and have some limitations:

- `beagle-hash`: it's a hash that could indicate if the local cache is equal to the server content. It was conceived initially to minimize payloads transfered by Beagle (**4.**), but it is just working with totally static content (**2.**), so it doesn't work as expected.
  - doesn't work for distributed backend scenarios, because the current implementation uses application memory to generate and store hashes
  - defaults to null

- `maxAge` this parameter says how much time we should cache a content.
  - its usage is currently coupled with `beagle-hash`, so it's restricted to the scenarios where `beagle-hash` is applied
  - if we decouple them, `maxAge` could be used to partially solve **2.**
  - defaults to a locally configured value

### Proposed Solution

Introduce a new parameter called `beagle-cache-strategy`. It could be one of the following values:

- `network-with-fallback-to-cache`: can be used to handle **1.**, since every request that uses this strategy will try to ask for new updates from network first, and then try to use cache if an error happened

- `cache-with-fallback-to-network`: it works for partially handling **2.**, so it always try to use cache, but if cache is invalid, it will request from server

- `network-only`: can be used in places that are more like **3.**, since it should never use a cache

Vocabulary for every strategy:

- "network" means requesting the most updated data from server
- "cache" means using a valid cached data (`maxAge` check cache validation here)
- and "fallback-to" means when some error happens it will use the alternative after "-".

This new parameter `beagle-cache-strategy` should have a default value configured locally on the application. The server could optionally pass a value for each request, if so it will override the default value of the application for that specific content. That way, our users can configure exactly what they want for different scenarios.

It can also be used in conjuction with `maxAge` parameter:

Example 1: `network-with-fallback-to-cache` + `maxAge` = always does a network request to get updated data, but when requested failed, it will use a valid cached data if avaiable. `maxAge` will be used here to verify cached data.

Example 2: `cache-with-fallback-to-network` + `maxAge` = uses valid cached data, but would make a network request when have invalid cache. Here `maxAge` will be used to verify cached data.

Example 3: `network-only` + `maxAge` = will always make network request, and ignore cache and `maxAge` value. It should not even store response as a cache.

If we can solve `beagle-hash` implementation problems, we could use it on all examples above, but it would only be applied to the "network step" of the strategy, not for validation of "cache step". That way, we could make it work for the real purpose we wanted (minimize payload). So, whenever we make a network request that has a `beagle-hash`, the server could respond to us that the response is unchanged, and we can use our previously cached version, without actually validating `maxAge`.

**Comment by ze12augusto** [comment]
Summary of what was defined at the meeting on the 9/3/2020:

1 - Make tests related to different flows to test if the problems we raised about our implementation really exist and if it would be interesting for the beagle to solve them
2 - Test beagle-hash being recalculated at every endpoint and compare performance / payload size using beagle movies application as a base
3 - Separate ttl from the beagle-hash (front + back) and let the default value (30) be customized by the user
4 - If it is validated in our tests that we need to deal with the fallback scenario for cache, we must implement a logic to define this by endpoint and return as a header in the response so that the front can recognize and follow this flow
5 - Adjust storage of endpoint hashes for the user to be able to customize in a simple way (ex use distributed datasource to store data, such as redis)
