### ISSUE TITLE
Improve depreciation messages

### ISSUE THREAD

**Issue by matheusribeirozup** [ZupIT/beagle#849]
## Use case

When using any deprecated attribute, method or class in Beagle, we receive a depreciation message, however in most cases there is no `ReplaceWith` shortcut.

## Proposal

Add the `ReplaceWith` attribute for all depreciation messages to give the user a shortcut to replace the deprecated attribute, method or class.

**Comment by matheusribeirozup** [comment]
Since the components that are depreciated obligatorily after some versions will be removed from the source code, it is interesting to contain in the depreciation message **which current version** of the Beagle it was added to, so that we know when we can remove it.

**Comment by tuliopereirazup** [comment]
Merged with #903
