### ISSUE TITLE
Infer Bind.Expression types in constructors

### ISSUE THREAD

**Issue by matheusribeirozup** [ZupIT/beagle#852]
## Use case

When any component that receives a parameter of type `Bind` parameter is constructed in the local Beagle Android declarative, that attribute is inferred to be a `Bind.Value` even if it is an expression.

## Proposal

It would be better for the user if for every component that receives some attribute of type `Bind` as a parameter, validate if it contains an expression so as to type it as `Bind.Value` or `Bind.Expression`, as in the image below:

<img width="657" alt="Captura de Tela 2020-08-28 às 18 55 35" src="https://user-images.githubusercontent.com/57918064/91619781-7066ad00-e964-11ea-83be-4810a19ac002.png">

**Comment by uziasferreirazup** [comment]
instead of check if the expression in all the constructors why not put this logic inside the method `expressionOf`

**Comment by matheusribeirozup** [comment]
I agree to extract to another class or method, I put an example in this issue simply to have a visualization of the problem. Thanks for the comment 😊
