### ISSUE TITLE
[Question][Android] Do we have instrumented tests?

### ISSUE THREAD

**Issue by othiagosouto** [ZupIT/beagle#859]
Hey, checking Beagle framework and I did see some `androidTestImplementation` declared on [android/bealge/build.gradle](https://github.com/ZupIT/beagle/blob/master/android/beagle/build.gradle) but i didn't see `androidTest` folder.

Do we have instrumented tests for that? What's the strategy here?

**Comment by tuliopereirazup** [comment]
Hi @othiagosouto, as we are preparing our integration and snapshot tests and it is not integrated in our pipeline, all tests are in a specific branch, see here: https://github.com/ZupIT/beagle/tree/feature/automation-structure.

**Comment by uziasferreirazup** [comment]
Hello @othiagosouto finally the instrumentation test was merged in the master.

There is a simple documentation to know how to run the instrumentation test: https://github.com/ZupIT/beagle/blob/master/AutomatedTests.md, but if you run some instrumentation test in any application android it is equal.

the current module has the instrumentation test:
https://github.com/ZupIT/beagle/tree/master/android/automated-tests

Now the current strategy:
All the new features developers in the beagle need to has an instrumentation test(it is required).
The team focusing in create more scenarios and cover all the components and the features.

The process to release:

the process to run the instrumentation test in current CI / CD has not yet defined.


I will close this issue, but if you have any doubts feel free to re-open or create another one.
