### ISSUE TITLE
Add Toolbar itens parameter to TextInput

### ISSUE THREAD

**Issue by yandiaszup** [ZupIT/beagle#901]
## Use case

There is no way to call onBlur action in inputTypes that use the numeric keyboard, because it does not have a done or return button that we can tap it and dismiss the keyboard

## Proposal

Add a parameter that represent a list of ToolBar items that will be presented on top of the keyboard like this:

<img width="242" alt="Screen Shot 2020-09-11 at 14 35 16" src="https://user-images.githubusercontent.com/42281214/92955710-08bc6180-f43c-11ea-8991-3117d3847180.png">

UIKit numeric keyboard:

![Screen Shot 2020-09-11 at 14 42 12](https://user-images.githubusercontent.com/42281214/92956278-00185b00-f43d-11ea-9dff-42807c4349a8.png)

## Code

```
public struct TextInput: RawWidget, AutoInitiableAndDecodable {
    ...
    public let toolbarItems: [ToolbarItem]?
    ...
}
```

## Common Issue

#900

**Comment by paulomeurerzup** [comment]
On Android we do have ACTION_DONE. Could we remove Android tag from this issue?
![Captura de Tela 2020-09-14 às 11 13 47](https://user-images.githubusercontent.com/66129650/93097148-920da700-f67b-11ea-9301-45331e5d6d2e.png)
