### ISSUE TITLE
[iOS] SendRequest is missing some bindable fields

### ISSUE THREAD

**Issue by LG95** [ZupIT/beagle#920]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
The `SendRequest` action's definition in iOS has two fields as non bindable when other platforms have them as bindable. The fields are method and headers. Below is the backend definition as an example.
```kotlin
data class SendRequest(
    val url: Bind<String>,
    val method: Bind<RequestActionMethod> = Bind.Value(RequestActionMethod.GET),
    val headers: Bind<Map<String, String>>? = null,
    val data: Any? = null,
    val onSuccess: List<Action>? = null,
    val onError: List<Action>? = null,
    val onFinish: List<Action>? = null
)
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a `SendRequest` with an expression to evaluate for its method or headers in the BFF.
2. Call this BFF from an iOS app.

## Expected Results
Successful evaluation and binding of the method and headers.

**Comment by gabcoelho** [comment]
Closed in #927
