### ISSUE TITLE
Add documentation to all public APIs that is missing java doc

### ISSUE THREAD

**Issue by tuliopereirazup** [ZupIT/beagle#947]
## Description
Everything that is public API should be documented using javadoc notation, because some public APIs is missing.

## Steps To Reproduce
We have some examples like: RootView, ActivityRootView, FragmentRootView, DeepLinkHandler, StoreHandler, etc.

## Expected Results
Add javadoc documentation to all public APIs.

**Comment by luisoliveirazup** [comment]
#971  issue related to class documentation on the backend

**Comment by luisoliveirazup** [comment]
#975 issue related to action documentation on the beagle android

**Comment by luisoliveirazup** [comment]
#976 issue related to components documentation on the beagle android
