### ISSUE TITLE
Use the loadView ServerDrivenState listener

### ISSUE THREAD

**Issue by FredericoNoce** [ZupIT/beagle#954]
## Use case

When I load the screen through loadView, I'm already passing a screen state listener that implements a way to show a load on my screen. I wish I could change that same state of the screen so that I don't need to implement an action to show that same load.

## Proposal

At any point in my BFF I can change the state of the screen, so that I can use the loadView implementation.

**Comment by uziasferreirazup** [comment]
for now this will not be prioritized, I will close this issue, but we are always thinking about improvement and this issue may come up again.
