### ISSUE TITLE
[Android] - Declarative sendRequest in Android not return success.data value

### ISSUE THREAD

**Issue by jefersonlopeszup** [ZupIT/beagle#957]
## Description
When receiving an object through SendRequest, in declarative Android screen,  it is not possible to update a context

## Steps To Reproduce

1. Receive an object through SendRequest in Android declarative
2. Use setContext or Alert passing the received object

## Expected Results
Hope the context is updated correctly and Alert showed the JSON value

## Code example, screenshot, or link to a repository:

```
SendRequest
= listOf(
     SendRequest(
        url = "https://covid-19-data.p.rapidapi.com/totals",
        headers = mapOf("x-rapidapi-host" to "covid-19-data.p.rapidapi.com",
        "x-rapidapi-key" to "d5fcaeee39msh4ccd86eeb3f8db4p15338bjsn32b45a87d8ea"),
        method = RequestActionMethod.GET,
        onSuccess = listOf(
               SetContext(
                      contextId = "coronaData",
                      value = "@{onSuccess.data[0]}"
               ),
               Alert(
                     title = "Teste",
                     message = "@{onSuccess.data[0]}"
         ))
)
```

Data class
```
data class CoronaData(
        val confirmed: String,
        val recovered: String,
        val critical: String,
        val deaths: String,
        val lastChange: String,
        val lastUpdate: String
)
```

Expected: Json Object to pass in Context and Alert
Returned: String "@{onSuccess.data[0]}"

**Comment by jenifersantoszup** [comment]
I tested this code example both by declarative mode on android and by bff and using .values ​​and worked.
